### ISSUE TITLE
Find solution for earlier v4 tip discovery

### ISSUE THREAD

**Issue by SwenVanZanten** [vergecurrency/verge#1061]
Find a fix for https://github.com/vergecurrency/verge/pull/974
This was initially implemented to have compatibility with v4 nodes.

v4 nodes are now obsolete.

This change might needs reverting as its causes security issues.

**Comment by zawy12** [comment]
The attack was easy because chain work was was replaced with height **[here](https://github.com/vergecurrency/verge/blob/43a625b19ea2c340df2e643d0f020ceac4d9b445/src/chain.h#L374).**  

Using multiple POWs makes the difficulty algorithm (DA) and calculating chain work problematic. Pigeon, Raven, and Myriadcoin (which I think Digibyte and Pyrk copied) seem to have gotten the issues worked out.  It may be difficult to import their method(s).

I don't know if just reverting will be a fix.  The previous attacks seemed to be based on the problems caused by multi-POW.  I am doubtful it was ever fixed.  So I would copy one of the above coins or use the following idea.

It is possible to stick with height.  The problem occurred because the current DA was >10% behind schedule. This allowed the attacker to start off using long solvetimes to lower the difficulty and still end up with a higher height in the same amount of time.  There is a certain sequence of timestamps attackers can use that allow various DAs to emit more blocks than the normal random solvetimes.  ETH's DA could be tricked to issue 75%  too many blocks with the same amount of work.  SMA algos can be tricked into emitting 50% too many.  WTEMA/ASERT can be tricked into 38% too many.  LWMA is the only one I can't trick over short time scales, so it seems to be the only one where you can use height in place of chain work with only a little bit of error.  Difficulty would be determined by scanning the previous blocks until N=300 blocks with the POW the miner wants to use are encountered. The nBits target in headers would be based on the POW and its value calculated based only on previous blocks that used that POW.  The target solvetime between blocks for each of the 5 POWs would be 5 * 30 = 150 seconds. Chain work would just be the height.

But this needs to be combined with a limit on reorg depth because even LWMA can be tricked if you back in time far enough.  I don't know what the exact numbers are, so this is just an estimation. The attacker might be able to make solves per hash 0.5% faster than normal random solvetimes in an LWMA by setting the timestamps exactly equal-distance apart (equal to the target block time).  If the LWMA has N=300 then he can make his 1st 150 timestamps say 5x the target block time apart to make difficulty something like 1/4 normal what it was. Then he would start with the equal-distance timestamps which recovers the time in the long solvetimes.   He would have to start with a block in the distant past that is more than 150 * 5 / 0.005 = 150,000 blocks in the past to initially lower difficulty like this and then end up at a slightly higher height as the public chain in the same amount of time with 1/4 the hashrate. So you would have to outlaw reorgs that are more than say 10,000 blocks.  But this requirement allows a Sybil attack on reconnecting nodes that can force a chain fork, so you have to have trusted nodes which is an unwanted centralization.

**Comment by zawy12** [comment]
Simply reverting #974 like @SwenVanZanten says looks like it would have prevented this problem.  But only x17  and lyra2re are really adding to chain weight.  It would be good if the weightings could be updated, with the new weights becoming active after some height. Judging by the current difficulties 3 of the 5 weightings appear to be off by a factor of 100. I put the implied corrected weightings below as a comment on the current code.  X17 was my baseline (I kept it 6 * 1000000).  Theoretically, the market is efficient and the current difficulties reflect current cost to mine which reflects the rewards which reflects the truest chain weight.  But if there is a more accurate metric of cost to mine, tt should be based on actual cost because if for some reason no one is currently using scrypt and this is incorrectly causing its factor to be a high 200x, then an attacker wanting to rewrite the chain would just rent scrypt and mostly use it. The whole problem with multi-POWs is that these factors change over time.

https://github.com/vergecurrency/verge/blob/43a625b19ea2c340df2e643d0f020ceac4d9b445/src/pow.cpp#L472 
```
unsigned int GetAlgoWeight(int algo)
{
    switch (algo)
    {
        case ALGO_GROESTL:
            return (unsigned int)(0.005 * 100000);   //  1 * 100000 (based roughly on current difficulties)
        case ALGO_BLAKE:
            return (unsigned int)(0.00015 * 100000);  // 0.07  * 100000
        case ALGO_X17:
            return (unsigned int)(6 * 100000);  // 6  * 100000
        case ALGO_LYRA2RE:
            return (unsigned int)(6 * 100000);  // 3  * 100000
        case ALGO_SCRYPT:
            return (unsigned int)(1.4 * 100000); // 200  * 100000
```

The DGW3 algorithm being used is just a simple moving average in disguise. The min and max blocks shown here 
```
    long long PastBlocksMin = 12;
    long long PastBlocksMax = 12;
```
are incredibly low which causes the difficulty to vary wildly.  These values should be 100.  The LWMA in the code should not be used.  It has a horrific exploit. 

Here are the changes I see as needed if someone does a pull request. Remove the 1/3 and 3x timespan limits in DGW3 for blocks above the the next fork height.  Change peer time from 70 min to 5 min (previous issue). Revert #974. Double check my chain work  weightings above and make them active after the next fork height.    Change min and max in DGW3 from 12 to 100.

**Comment by zawy12** [comment]
The precise definition of "chain work" when compared across POWs and coins is the amount of real-world value like dollars that a competitive marketplace is willing to spend to get the rewards and fees. assuming the rewards plus fees per block are about constant and the marketplace between algos is competitive, the amount of real world chain work spent on each block should be about the same.  It has little to no relation to the number of hashes from different algos, but the "work" is the "energy" aka "real world value" spent on the hashing.

**Comment by SwenVanZanten** [comment]
> Simply reverting #974 like @SwenVanZanten says looks like it would have prevented this problem. But only x17 and lyra2re are really adding to chain weight. It would be good if the weightings could be updated, with the new weights becoming active after some height. Judging by the current difficulties, the other 3 POW weightings appear to be off by a factor of 100. They rarely add any work to the chain. Theoretically, the market is efficient and the current difficulties reflect current cost to mine which reflects the rewards which reflects the truest chain weight. In other words under the efficient market hypothesis, a scaling factor applied to the current difficulties of each POW to make them all equal is the scaling factor that's needed to assign the correct chain work. I looked at a few block's difficulties and put the implied corrected weightings (scaling factor) as a comment beside the current code below. X17 was my baseline (I kept it 6 * 1000000).
> 
> If there is a more accurate metric of cost to mine, it should be based on actual cost instead of my scaling factors because if for some reason no one is currently using scrypt and this is incorrectly causing its factor to be the high 200 factor below, then an attacker wanting to rewrite the chain would just rent mostly scrypt. The only requirement I saw in XVG is to not use the same POW algo 5x in a row. If attacker is required to use them all with the same frequency (as in other coins) then these scaling factors are not as crucial, but still need to be roughly correct. The only problem with multi-POWs is that these factors change over time. Otherwise multi-POW seems to make 51% attacks harder, if they are required to be used with equal frequency. If the only requirement is that the same POW is not used for more than 5 blocks in a row, the chain is as weak as the weakest POW (the cheapest to rent for the given scaling factor).
> 
> https://github.com/vergecurrency/verge/blob/43a625b19ea2c340df2e643d0f020ceac4d9b445/src/pow.cpp#L472
> 
> ```
> unsigned int GetAlgoWeight(int algo)
> {
>     switch (algo)
>     {
>         case ALGO_GROESTL:
>             return (unsigned int)(0.005 * 100000);   //  1 * 100000 (based roughly on current difficulties)
>         case ALGO_BLAKE:
>             return (unsigned int)(0.00015 * 100000);  // 0.07  * 100000
>         case ALGO_X17:
>             return (unsigned int)(6 * 100000);  // 6  * 100000
>         case ALGO_LYRA2RE:
>             return (unsigned int)(6 * 100000);  // 3  * 100000
>         case ALGO_SCRYPT:
>             return (unsigned int)(1.4 * 100000); // 200  * 100000
> ```
> 
> The DGW3 algorithm being used is just a simple moving average in disguise. The min and max blocks shown here
> 
> ```
>     long long PastBlocksMin = 12;
>     long long PastBlocksMax = 12;
> ```
> 
> are incredibly low which causes the difficulty to vary wildly. These values should be 100. The LWMA in the code should not be used. It has a horrific exploit.
> 
> Here are the changes I see as needed if someone does a pull request.
> 
> * Remove the 1/3 and 3x timespan limits in DGW3 for blocks above the the next fork height.
> * Change peer time from 70 min to 5 min (previous issue). This can likely be a hot-fix.
> * Revert #974. ( Go back to nChainWork instead of GetBlockWork() which uses nHeight.)
> * Double check my chain work  weightings above and make them active after the next fork height.
> * Change PastBlocksMin and PastBlocksMax in DGW3 from 12 to 100 (least crucial issue)
> 
> This fixes all the exploits I'm aware of.

Thnx for your input @zawy12 those are reasonable changes.

This is also a possible solution: https://github.com/tpfuemp/VERGE/commit/2dffb7884d69c79f17d4e90b6fd777611867db74

**Comment by tpfuemp** [comment]
to complete fixing peer timings needs to lower too.
and averaging needs some justification to better values.

**Comment by zawy12** [comment]
I was looking at the ApproxNthRoot() calculation (aka Geometric Mean) this morning instead of your scaling I was trying to correct above.  It looks like a pretty clever idea. I am curious who thought of it.  Averaging methods I was thinking of (to replace the errors due to hard-coding scaling) have exploits, but this GM does not.  The work assigned to the current block is based on the geometric mean of the difficulties that will be assigned to each of the algos in the _next_ block.  I emphasize _next_ because that's a little wasteful because this means they have to run the DA 5x for each block just to get the work.  It's just as good ito read the difficulty from the previous block of each algo. This matters less for Digibyte and others that use Digishield as the DA, but DGW has that loop in it that adds computation, especially if you change it to 100 blocks like I'm saying.  500 iterations per block like this isn't a lot when computers probably do 10 million a second (this would mean 500 extra seconds to resync a 10M block chain).  Switching to Digishield would be good. It might be easier to look at Pyrk code than digibyte.

You don't need to use any scaling with the geometric mean, or at least you should not change the scaling after you start using it.

**Comment by justinvforvendetta** [comment]
yeah geometric mean is nice and auto scalable.

**Comment by marpme** [comment]
This what has been proposed from our digibyte friends back in the days when researching a more reasonable way of doing chainwork calculations: https://github.com/vergecurrency/verge/pull/969

**Comment by tpfuemp** [comment]
ok, nearly the same code porting like i did. why was this solution not pursued further (in halving hardfork)?
