### ISSUE TITLE
Qt wallet not receiving coins

### ISSUE THREAD

**Issue by Argo1111** [vergecurrency/VERGE#107]
Hey guys, I would very much appreciate your advice/help since I don’t have technical background and don’t know what to do. 

This is what happened:
a) I downloaded desktop Verge Qt Wallet for Mac, downloaded blockchain, let the wallet synced. I also backed up my wallet. 
b) I sent a small amount of XVG to the wallet via Changelly and everything worked just fine, I received the coins within an hour.
c) Then I send a large amount of XVG to the wallet via Changelly, but during the process my internet connection went down which I did not noticed.
d) Now (when I restored the internet connection after about 10 hours) I am at the point when Changelly page still reads “Sending to your wallet, your money has been exchanged, blockchain is confirming your transaction” and it is stuck like that for many many hours. 
e) Wallet synced when the internet connection restored (it reads “up to date”), but the coin not received. I cannot seems to find the transaction in the blockchain.
f) I backed up my wallet again just to be sure.

I don’t understand in detail how this desktop wallet works and would appreciate your input. Can this issue be caused that the wallet lost internet connection within the process? Is there anything I can do now?

Thanks a lot, Daniel

**Comment by justinvforvendetta** [comment]
try deleting the blockchain data and syncing it from scratch

**Comment by fireman50** [comment]
did you get it figured out?

**Comment by Argo1111** [comment]
Thanks a lot guys, it was sorted out... Thx...

**Comment by badbrainIRC** [comment]
you have to log back changely and see if money have been sent in the history of your account.

Sent from my Bell Sony device over Canada’s largest network.

---- Argo1111 a écrit ----


Hey guys, I would very much appreciate your advice/help since I don’t have technical background and don’t know what to do.

This is what happened:
a) I downloaded desktop Verge Qt Wallet for Mac, downloaded blockchain, let the wallet synced. I also backed up my wallet.
b) I sent a small amount of XVG to the wallet via Changelly and everything worked just fine, I received the coins within an hour.
c) Then I send a large amount of XVG to the wallet via Changelly, but during the process my internet connection went down which I did not noticed.
d) Now (when I restored the internet connection after about 10 hours) I am at the point when Changelly page still reads “Sending to your wallet, your money has been exchanged, blockchain is confirming your transaction” and it is stuck like that for many many hours.
e) Wallet synced when the internet connection restored (it reads “up to date”), but the coin not received. I cannot seems to find the transaction in the blockchain.
f) I backed up my wallet again just to be sure.

I don’t understand in detail how this desktop wallet works and would appreciate your input. Can this issue be caused that the wallet lost internet connection within the process? Is there anything I can do now?

Thanks a lot, Daniel
