### ISSUE TITLE
Blockchain download invalid - still syncing from 0

### ISSUE THREAD

**Issue by bmatthewshea** [vergecurrency/VERGE#108]
1. Your blockchain download 'info'/help link is broken. https://verge-blockchain.com/
  _This site can’t be reached - verge-blockchain.com refused to connect._
2. The download link to zip file is invalid zip. It is a RAR file not a ZIP file!
3. I managed to unzip the "zip file", and put data in blockchain area.
4. The qt wallet is still syncing from 0.

![rar-not-zip-2017-12-16-094704](https://user-images.githubusercontent.com/984097/34072137-55a4b826-e247-11e7-98bb-46a35d6bcf32.png)

What's so hard about zipping (properly) the daily blockchain data?
You could even automate this daily.
Why does the file have '.ZIP' on end when it's really a .RAR? **There is no excuse for this.**

Why is the blockchain you offer (as a zip that isn't a zip) 11 months out of date? (Feb2017)

![out-of-date-bc-verge-2017-12-16-101508](https://user-images.githubusercontent.com/984097/34072299-4e99ad7c-e24a-11e7-866f-91ac1c4d1be3.png)

And why in the world is your website down that explains how to utilize the downloaded chain data? Shouldn't those instructions simply be added to the 'readme.MD'? Hmmm.

Speaking of the github readme, why is everything out of order?
Put you compile/build instructions together in one area for Linux, Mac, Windows.
Put your execution/wallet instructions together. 
You have no build instructions for Windows? Why? 
This part isn't rocket science if you want ppl to use your coin. -> Make it easy to use/setup!

**Comment by justinvforvendetta** [comment]
"1. Your blockchain download 'info'/help link is broken. https://verge-blockchain.com/"

ok, slow down. first of all, the site https://verge-blockchain.com/ is working just fine. (it's ran by a community member to help people that need help, like you, obviously.)

"Why does the file have '.ZIP' on end when it's really a .RAR? There is no excuse for this."

again, it's ran by a community member, and now i think you're talking about the cryptochainer site and not even the verge-blockchain.com site. but i have no idea, because you're starting to sound like a douchebag, and i'm losing interest in helping you. 

if its syncing from 0 then you downloaded the 2.x .zip file. there are 2 different .zip files on that site in case you didnt notice. (which you obviously didn't) the reason is because the 3.0 wallet has a different format for the blockchain data than the previous wallets.

what website is "down" that describes how to utilize the downloaded chain data?  also, where the hell did you download a file that is 10* months old? (not 11 months, because: math) 

we dont have build instructions for windows because its a very complicated process, and most windows users probably wouldnt be able to do it, and each wallet version ends up having a different method of compiling. if you're a windows developer, it should be fairly simple. if you are just a regular windows user, its not simple at all. anyway, im kind of over trying to help, because of your condescending tone (which is ironic because you're asking for help)

**Comment by bmatthewshea** [comment]
_(it's ran by a community member to help people that need help, like you, obviously.)_

My apologies about saying your site is down. My router blocks Ukraine.
As far as where I downloaded blockchain:

It's from your README for this project since you need help... obviously:

_Want to to download the blockchain instead of waiting/syncing? (quicker)
download this .zip file, and extract it to your verge data directory: https://verge-blockchain.com (follow the easy HOW TO instructions!) http://108.61.216.160/cryptochainer.chains/chains/Verge_blockchain.zip_

I could not load that web page, but I was able to download that blockchain. But that is not a ZIP file as mentioned.
