### ISSUE TITLE
7.1 release forgotten images

### ISSUE THREAD

**Issue by skironDotNet** [vergecurrency/verge#1101]
The release even writes "Compatible with latest Ubuntu 22" but no Linux, no OSX compilations, just windows exe

**Comment by decentralisedcoder** [comment]
Yes I had to build from source as there were no linux binaries available, but since building and using 7.1 I keep getting lots of these errors and it won't connect for long or sync and this is using the official bootstrap, my own from a working 7.0 release at home, the in place upgrade version from 7.0 -7.1 

2023-02-27T16:25:02Z [0%]...[16%]...ERROR: ReadBlockFromDisk: Errors in block header at FlatFilePos(nFile=53, nPos=39459474)
2023-02-27T16:25:02Z ERROR: VerifyDB(): *** ReadBlockFromDisk failed at 6585841, hash=7e7d4776bdf02c2c7794391e187430954da1eb4a5bca08258366055136d071b7
2023-02-27T16:25:02Z : Corrupted block database detected.

and this as well:

ERROR: AcceptBlockHeader: Consensus::CheckBlockHeader: 16db2ac4e3c6a646daf215d17d0b3941b1885b16db93570e2aa1ac2e868e8231, high-hash, proof of work failed (code 16)

Trying to reindex once more and if it fails I will need to downgrade back to 7.0

**Comment by skironDotNet** [comment]
that's why there is no issues because bots close them. What a shitcoin and a piece of shit team

**Comment by YuXiaoCoder** [comment]
@marpme The same issue was encountered in 7.2.0
