### ISSUE TITLE
Wallet out of sync

### ISSUE THREAD

**Issue by Timbovs** [vergecurrency/VERGE#114]
Hi there,
The Verge-QT 3.0 wallet keeps saying it's out of sync.
I've downloaded the blockchain but no luck.

My balance keeps saying it's 0.
I made a deposited to the "receive coins" provided me.

Can somebody help me?

**Comment by Timbovs** [comment]
Update, it's fully synced but my balance is still 0.
But i bought a decent amount on 17-12-2017.

**Comment by londoncoingatherer** [comment]
I'm having the same issue, i've downloaded the QT Verge wallet on Mac, sent coins to my wallet but it says "out of sync". 

When I first downloaded it there was a progress bar at the bottom, but it hasn't been there since. I've tried deleting the wallet and downloading again, restarting my computer etc and nothing works. 

I'm now worried i've lost the coins  I transferred fro Hitbtc.

**Comment by justinvforvendetta** [comment]
well, sounds like a firewall issue or something. check if you have connections in the bottom right.
