### ISSUE TITLE
Unable to open Electrum TOR 2.4 macOS High Sierra - Month 13 is out of bounds

### ISSUE THREAD

**Issue by MaGuSVa** [vergecurrency/VERGE#196]
I downloaded the titled, dragged and dropped it into Applications. When I open it, I get an Electrum-XVG Error.

The error is:

Month 13 is out of bounds

<img width="1228" alt="electrum-error-2" src="https://user-images.githubusercontent.com/34987026/34467190-1e152454-eeb8-11e7-89fa-79908569168a.png">
![electrum-error](https://user-images.githubusercontent.com/34987026/34467191-1e1f3b38-eeb8-11e7-901c-e43e917201b3.png)

**Comment by mnott** [comment]
Month 13 is out of bounds is a well-known issue with High Sierra. Google it. Has likely no impact and probably nothing to do with Verge.

**Comment by topcatx** [comment]
@MaGuSVa When you open the dmg, instead of clicking on `Electrum-XVG`, drag the icon to Application and then open it. This should resolve the error. 

We should probably do something to avoid this. I have seen few people download the wallet and then say it doesn't work, may be have a dragger from `Electrum-XVG -> Application` similar to what we have in the full wallet.

**Comment by jrsikors** [comment]
old issue cleaning up -- potential workaround provided , and electrum-xvg wallet will soon be "removed" .. no new development going into it.  Moving to the electrum tor
