### ISSUE TITLE
Public IP addresses?

### ISSUE THREAD

**Issue by dragGH102** [vergecurrency/VERGE#210]
I think Verge is a great project.
However, when I found this, I got quite astonished...: http://xvg.keff.org/

Is this source reliable? i.e. does Verge blockchain keep IP addresses linked to transactions? 
Because if so, I see no privacy here

Thanks for clarifying

**Comment by wertzuiop123** [comment]
dont post fud trash here...
You do realize there is an option for the transaction to be public OR private right? Or do you even read? That means, if chosen public...the IP address WOULD be visible

**Comment by wertzuiop123** [comment]
dont post fud trash here...
You do realize there is an option for the transaction to be public OR private right? Or do you even read? That means, if chosen public...the IP address WOULD be visible

**Comment by dragGH102** [comment]
@wertzuiop123 I do have some XVG, I have NO interest in spreading FUD. This is Github. Issues are meant to highlight issues.
If you provide a clear explanation (instead of just "can choose") I'll be happy to amend my comment.
Also reading of people being banned from Discord and everything, that's not nice

**Comment by dragGH102** [comment]
btw, @wertzuiop123 I see you joined Github TODAY. I believe accountability matters when making statements :) Please clarify and I'll be glad not just to amend my post but also write a post IN FAVOR or Verge

**Comment by sanecito** [comment]
@dragGH102 Yes, reliable source. Core wallet prior to the 4.0 release didn't have integrated Tor and leaked IP. New wallet (4. 0) despite containing Tor code doesn't actually obfuscate IPs which means it isn't private even according to Justin's (dev) definition. Connections to Last.fm and cryptoradio are also sent over HTTP and HTTPS.

https://twitter.com/Fuzzbawls/status/947807266111045632

**Comment by monceeef** [comment]
I tested and the transactions are really private , you sir are posting FUD and got it wrong .

**Comment by Fr4g3roO** [comment]
@monceeef hey , can you post some images so the whole FUD can be stopped

**Comment by justinvforvendetta** [comment]
radio is no longer connected. tor is integrated just needs to be put into the makefiles and the new update pushed

**Comment by Fr4g3roO** [comment]
@justinvforvendetta awesome work bruh, put it in twitter with images so the whole fuzz gets over xD

**Comment by sciack76** [comment]
exactly there is no radio in verge qt 4.0... Tor wasn't enabled yet. Just relax and everything will be fine.

**Comment by dragGH102** [comment]
Guys, chill. Verge is not just a money machine but technology. Discussions on potential issues are only healthy for the project in the mid/long-term. 
Provide clear explanations and I'll write a post anti-FUD :D

**Comment by anicca444** [comment]
PLEASE learn the difference between private/public ledger addresses and IP obfuscation (hiding your network IP)...

Wraith is supposed to enable hiding of private wallet addresses/transactions...

IP obfuscation (hiding your network IP), on the other hand has been well established within verge for a very long time. Utilizing the TOR (onion router) and i2p networks, wraith was not about this.

**Comment by dragGH102** [comment]
@anicca444 thanks for the explanation. I don't know Verge enough to confirm it's a good answer, but for now I consider it as such. Closing the issues and no FUD here ;)

**Comment by sanecito** [comment]
> Utilizing the TOR (onion router) and i2p networks, wraith was not about this.

@anicca444 It is according to Verge team. Multiple graphics from Verge team reference integrated Tor integration being a part of Wraith (although as noted above, all versions of Verge core wallet, Wraith or not leak your ResNet IP's which makes [Verge not private according to Justin/dev's own definition](https://twitter.com/Fuzzbawls/status/947807266111045632)):

For proof of Tor integration that is _supposed_ to be a part of Wraith see this [graphic](https://cdn-images-1.medium.com/max/800/1*-eYTD0HaOJPZE_6Pp0IMug.png) from https://medium.com/verge-currency-xvg/the-core-wallet-3-0-is-live-52cc4b59c9bb

And this [graphic](https://cdn-images-1.medium.com/max/800/1*y1vsKcCGFmsv41LW8SxUnA.png) from https://medium.com/verge-currency-xvg/meet-the-core-team-our-future-vision-and-an-important-announcement-3965730bd0b8

Or Justin's comment that Tor is integrated, but not released.

**Comment by justinvforvendetta** [comment]
this is where tor is being integrated, and its very near completion: 
https://github.com/vergecurrency/VERGE/tree/wraith-tor

**Comment by justinvforvendetta** [comment]
and yes, our android app has been hiding users ip addresses via onion since it was released.

**Comment by bryanx86** [comment]
It hid my IP. I did not find it in a search of the leaked ip's.

**Comment by sanecito** [comment]
> It hid my IP. I did not find it in a search of the leaked ip's.

@bryanx86 Your IP would have shown up if and only if you were connected to one of Jeff's nodes and broadcasted other people's tx or your own when the connection was open. Justin has admitted on this very thread that the core wallets for Windows, Mac, and Linux systems have not used Tor up to this point which means Justin et al have lied and scammed people on several accounts, not just the fact that Verge doesn't protect you from ledger analysis...but IP protection. Verge to date is still not 'completely untraceable'.

In other words you would have arguably been safer for IP obfuscation by using BitCoin + Tor via TAILS rather than use a Verge core wallet which has no IP obfuscation.

**Comment by justinvforvendetta** [comment]
what @sanecito ? i haven't lied about shit. get your facts correct. and no, bitcoin and tor isnt safer than verge you moron.

**Comment by bryanx86** [comment]
I know fud when I read it. This is GitHub tho, not twitter. Lol. Keep up the great work. I love the UI on the Android app. Dark theme.

**Comment by sanecito** [comment]
>i haven't lied about shit

From vergecurrency.com, your website:

> Verge uses multiple anonymity-centric networks such as Tor and I2P. The IP addresses of the users are obfuscated and the transactions are completely untraceable. 

Again see Jeff's website which logs ResNet IP addresses and the tx they relay/broadcast or the fact that [Verge has a rich list](https://verge-blockchain.info/richlist) which can only exist because Verge tx are traceable.

Yes Bitcoin over Tor (namely the TAILS bundle) is arguably notably safer than a Verge core wallet which offers no IP obfuscation. Namely because it has significantly more developers on the project who follow OSS standards when committing, reviewing, testing, merging, and releasing code so you don't have wallets crashing when opened like with Verge's recent release (#181 ) or people losing 88,000 XVG (roughly 14K USD at time of writing) as is the case with #151 

We are rather getting sidetracked from the issue topic at hand of Verge still leaking ResNet IP's though. So... sorry your own project isn't private by even your own definitions; the world does need more privacy focused projects, abet ones that work and don't lie. Best of luck getting your Verge core wallets to run over Tor bug free.

**Comment by CryptoSyndrome** [comment]
@dragGH102 hey drag, in general any reliable source will provide the steps of reproducing the steps which lead to his conclusion. I asked the owner of the tweet (which had that site as his " evidence " of the leaked IP) about the steps he made to collect the claimed leaked IPs. no answer until now.

**Comment by justinvforvendetta** [comment]
@CryptoSyndrome running netstat on the p2p port of a core wallet returns users and nodes that are connected to it. the verge electrum and android wallets do not do that, and we are making this core wallet retain user ip as well, but integration of tor, in the wraith-tor branch. it's near completion now.

**Comment by justinvforvendetta** [comment]
as seen in this article: https://themerkle.com/moneros-ip-address-leak-isnt-an-exploit-and-doesnt-affect-anonymity/

some people think it isn't a huge flaw to expose ip, but here at verge, we take that seriously, and do think it is a huge problem, which is why we release tor and i2p wallets in android and electrum, and now, this one will be as well.
