### ISSUE TITLE
Marketing / Tweet

### ISSUE THREAD

**Issue by VergeMarketing** [vergecurrency/VERGE#280]
Tweet for wallet 4.0.1 release

![verge](https://user-images.githubusercontent.com/35048684/34504460-c15dd3fc-f059-11e7-8645-55bb2bdf6957.jpg)

**Comment by dbtftw** [comment]
I feel like there should be no need to acknowledge FUD. Also saying lets go to the moon seems cheesy, and Cryptokboi ~ish

**Comment by dbtftw** [comment]
Otherwise i like it

**Comment by jcodemad** [comment]
My 2 cent 

Remove the Let's go to the moon! please, is very unpleasant right now to people that are losing a lot and is no credibly right now

**Comment by justinvforvendetta** [comment]
absolutely not. we arent going to be making tweets just for hype. we announced the release. we also tweeted that we're making updates. everyone that is actually in verge, knows whats going on.

**Comment by pcp1985** [comment]
Man, I just loved your above statement... that shows the quality!  Kudos and salute from my side for all the sleepless night and effort you put forward to make it the truth!

**Comment by jcodemad** [comment]
I totally agree, but "everyone that is actually in verge, knows whats going on" is not truth people need hope to stay, and a $2Billion Lead must given them that.

**Comment by bharadwaj003** [comment]
Agree with @jcodemad ..people don't understand tech ..they just look at what was promised and what was delivered 
For next major releases, business wise it makes more sense to test rigorously a week before deadline. 
Please continue this Awesome work

**Comment by jcodemad** [comment]
Write code never make a company great, having go ideas and team in place do build them and communicate very clear is what makes the difference. 
Steve Job never need to assemble Iphone pieces but he has a vision, Verge also but 

Investors (whales) don't care about github, they don't understand these things, 
Hire a real PR team and make sure they work side by side with the DEV team.
Hire more developers, and post on twitter showing you're hiring and growing as a team.

Realize you are a project currently valued in over a BILLION DOLLARS, please give the impression you are one so that the investors from Korea and Japan are willing to dump some more Millions your way.

**Comment by paradoxicalNL** [comment]
You guys did a great job. You understand I'm going all in now, as I tested your work and it's fully legit. +many kudos for your dedication.

**Comment by polyfonik** [comment]
Come on man.  You announced the release?  People are still tweeting "wraith coming soon!"

Please take some advice from marketers and business operators and announce the release properly so we can all get back on track and keep focused on the amazing future of your creation.

**Comment by sasasavic82** [comment]
Justin (@justinvforvendetta), I am a huge supporter and a holder. I am on holidays right now (no laptop) but I will be starting to make significant contributions as of next week, and will apply all of my industry and academic knowledge to this cause. I value you engineering proclivity, dedication and success. I'd love to somehow be an "advisory figure" (for the lack of a better word) and a sounding board, supporting your existing team (from an engineering and PR perspective). 

I agree with your above-mentioned statement, and equally I don't agree with the above-mentioned "tweet", however I do think (and no disrespect to existing practices), but it may be worth you revisiting the existing comms practices; it's fair to say that in this "cut-throat" ecosystem, we want to preserve integrity and continuously provide the masses re-assurance - we don't want to get to a "point of no return", or a situation where FUD-ers get the upper hand.

I know that this is a great product, and the value it brings is unfathomable ... so let's continuously keep reminding people, convert it to a language that general public and population understand, so they know their investments are safe and for the long term. My father today asked me "what ie Verge", and has transferred some $$$ to my CoinSpot account for me to invest for him. He did this because I explained to him what crypto is about, and more specifically, what benefit Verge brings to this new paradigm. As a bit of a "patriot" that has been burned by war (I'm from the Balkans), he understood the power of decentralization and freedom for privacy.

If I can now act as the voice of all of the people - from new comers to old-timers, from FUD-ers to supporters - let's kill the doubt, with power of positive words. Our voices need to be strong, and come from the most influential individuals. Let's start having a stronger presence in all the social media outlets.

**Comment by huynhhb** [comment]
Thanks for you and everyone's hard work. Looking forward to Verge's future!

**Comment by joaomscosta1** [comment]
You are loosing the oportunity to educate people in order they can understand how important can Verge be. Also, the tweets you made about the release were not objective. Take some advice from people who believe in this project and work on that part, so all of us can keep holding this.

**Comment by paradoxicalNL** [comment]
This product will sell itself, doesn't need marketing. The reason for me to stay in this project is just that, dedicated dev's. Wish I had time to contribute.

**Comment by zen98** [comment]
Justin (@justinvforvendetta),
Mate I agree with your stance about marketing but things have changed.I have been on twitter since xmas and before trying to keep people positive about verge. I have been trying to rebute people who have called verge scam coins and talked trash towards dev. I believe in what your project stand for. Your project has endured multiple FUDS , blackmail attempt etc. 
I honestly believe tweet from you stating it has been released on twitter would make a huge difference.and take a bow because you all deserve it after the long long hours you have spent.I will defend verge on twitter and hold.

**Comment by KundaliniEnergy** [comment]
@justinvforvendetta 
I am so grateful for all the work you and the team are putting in. I manage multiple social media accounts myself and would like to say that you are doing a good job but there is definitely room for improvement. Opening up a public AMA is a great idea, more interaction and replying to real peoples comments will help this coin tremendously. We have a wonderful community, and with the aid of a stronger PR plan and strategy this coin will absolutely excel. Communication is key and having a reliable team that is informed and can answer questions and keep people updated multiple times a day ex: 3-5 tweets, would go a long way. Anyways thanks again wishing you all a great day and a blast off into the next year.
