### ISSUE TITLE
Verge QT exe is not responding

### ISSUE THREAD

**Issue by d3v3agl3** [vergecurrency/VERGE#302]
after install on windows, suffered fatal error could not start.. deleted all files from appdata/roaming and re run, extracted blockchain zip into appdata/roaming, now keeps stopping on loading block index..

**Comment by techpoy** [comment]
It takes time to load the index. Give time till it loads the index fully. It took about 10-15 mins for me

**Comment by rvrhee** [comment]
would it possible to make some progress output on the splash screen ? or a message please be patient so many people thinks its crashed wile loading the block-chain.

**Comment by spruitmans** [comment]
I installed it with de blockchain  for me it also take about 15 minutes to start of
But when its is started (windows version) it runs smoothly 
sending and receiving verge coin is absolute fast

**Comment by d3v3agl3** [comment]
OK i kept getting windows message saying QTx64 has stopped, bars load across and it closes itself

**Comment by fradelo** [comment]
Indexing should run in a different thread because it locks the UI thread and system assumes the application halted which is not.

**Comment by spruitmans** [comment]
Question do you change your settings? And have you download the blockchain
https://verge-blockchain.com unzip the file in you %appdata%\VERGE
![image](https://user-images.githubusercontent.com/5248784/34517326-db816e44-f07a-11e7-9dc7-697ba2585752.png)
2nd question Did you allow you're firewall accept inbound/outbound traffic
![image](https://user-images.githubusercontent.com/5248784/34517488-80f1fdbc-f07b-11e7-8509-7b38797b88bd.png)
Does it runs now? otherwise sent print screens statusbar was close though it came back system is not halted see you're taskmanager

**Comment by d3v3agl3** [comment]
Yes did all as above.. am having another go now.

**Comment by d3v3agl3** [comment]
Deleted everything and downloaded from github again, set and run. All working fine now.

**Comment by KenShields** [comment]
My Verge wallet was working perfectly yesterday.  Today, it disappeared and when I downloaded the Verge-qt.exe from my backup and ran it, McAfee shouted at me that the file was infected.  When I download a new Verge for Windows wallet, it won't extract the two files in there and all I get is an empty directory.
Anyone else have an issue like this?
