### ISSUE TITLE
Product management help

### ISSUE THREAD

**Issue by 9b** [vergecurrency/VERGE#375]
@justinvforvendetta @jlaureano any interest in help from an information security product manager and developer?

**Comment by cngkaygusuz** [comment]
Can't speak in the name of them, but I reckon the expectation is just to barge in, take a look around and see what you can do to improve the project.

**Comment by 9b** [comment]
Less a barge and more of a helpful cleanup. There's a lot of value in organizing a release and planning media attention around it. A lot can be gained just in improving the documentation in using various tooling that's been created. Blogs covering privacy and potential use cases for the coin would provide those on the outside with reasons to support the project. Partnerships and backing by larger names would add legitimacy. Product management just brings some organization to provide the best possible solution for the end user.

**Comment by cngkaygusuz** [comment]
I completely agree with you. What I'm saying is, don't expect a coordinated plan with the developers before you do what you have said, especially at this stage where you are a complete stranger and people are not informed of your competencies. Instead of saying

> Hey, if we change the website in this particular way, things will look better. Should I do it?

I suggest doing something like

> Hey, I have modified the website in this particular way. I think it looks better, take a look.

After your suggestions are repeatedly found valid and you have established a reputation for yourself, people will start to trust you. Only then you will be trusted with such tasks. But before, just try to look around and see how you can contribute.

Note that these are just my opinion based on my perception of the community. Take it with a grain of salt.

**Comment by brianerdelyi** [comment]
FYI, I have started to form Verge-CSIRT and pushed a charter.  https://github.com/vergecurrency/vergecurrency.com/issues/253
