### ISSUE TITLE
Windows wallet 4.0.1 stuck transaction

### ISSUE THREAD

**Issue by dalojikal** [vergecurrency/VERGE#428]
# Issue Template

## Expected Behavior

expected the transaction to send with the correct fee so it will complete and not get stuck.

## Current Behavior

transaction fee was too low and transaction has remained unconfirmed for 3 hours at this point.

## Steps to Reproduce (for bugs)

* Steps :
1.
2.
3.
4.

## Your Environment

* Verge Release:
* CPU: i7
* GPU: Nvidia 970
* RAM: 16 GB
* OS:
    - [ x] I'm using WIN
    - [ ] I'm using Linux
    - [ ] I'm using Mac

## Any extra information that might be useful in the debugging process.

transaction ID 43c09a3091822aa0b1fb107007238fac918a35dd8673907d98900554feaca2c2

**Comment by justinvforvendetta** [comment]
what was the fee? the stealth txs will start going thru once the pools finish updating

**Comment by dalojikal** [comment]
it was 0.1 xvg for ~72 xvg transaction. Still showing 0 confirmations and I didn't think this was a stealth transaction...

**Comment by imthebackwardsman** [comment]
I have the same issue, sending to a stealth address doesn't work. I dumped the private key, made a new wallet, imported my private key, tried sending to a normal address, now i'm stuck with 0 confirmations again. I don't know if the problem is on my end or not, according to everyone else it is working.

**Comment by justinvforvendetta** [comment]
just waiting for all the pools to update and stealth txs will be confirmed
