### ISSUE TITLE
Stealth integration into pools

### ISSUE THREAD

**Issue by Positivism** [vergecurrency/VERGE#432]
I'm constantly kicked/banned from whatever platform I ask genuine questions on so I'm taking to git.

All concerning stealth:
What is the status on pools?
Why did we have a stealth release before pools were operating?
Why subject people to stealth transactions before they could successfully be carried out?

**Comment by Positivism** [comment]
You do realize anything sent via stealth is now frozen, whether by intention or not people are now not only being forced to hold verge but are also unable to use it because of the lack of forethought into the release procedure.

**Comment by justinvforvendetta** [comment]
we asked the pools to update and they are. transactions will be processed once the majority have updated.

**Comment by Positivism** [comment]
Why release before the pools were ready?

**Comment by justinvforvendetta** [comment]
also I've already spoken with our largest pool and they will be updating tomorrow

**Comment by justinvforvendetta** [comment]
everyone was notified at the same time. pools aren't given a release ahead of time, everyone gets it at the same time when it's ready

**Comment by Positivism** [comment]
Thank you.

**Comment by justinvforvendetta** [comment]
no problem. was a legit question. no one should ban for that. it has been asked here before though in a previous issue.

**Comment by Positivism** [comment]
Mind throwing me an invite to the discord/unbanning me? https://discordapp.com/invite/vergecurrency returns expired

**Comment by Ondalf** [comment]
Thanks for getting pools into this mess. No possible way to run multiple instances on same machine. Was that intentional? Hint: https://github.com/vergecurrency/VERGE/blob/master/src/init.cpp#L41 and whole torrc thing. Imagine 4 algorithms running on single machine, not separated, so far, not a single possible way to do this. One cannot run it without tor, since tor thread starts by default and if the thread drops, wallet cannot find the onion address and kills itself. "Yay" for quality release.

**Comment by michpiatek** [comment]
@Ondalf How about running separate tor then start VERGEd with -tor=127.0.0.1:PORT?

**Comment by Ondalf** [comment]
Have you? No, it does not connect. Converted from 4 perfectly working 3.x.x instances with separate algos into this 4.x.x caused only single wallet to rise up. -tor=127.0.0.1:9089 (which is default) works once. Second will (surprise) complain about being in use, and if launched to separate port, the tor daemon, the Verge wallet will initialize the tor daemon anyways and launch into that same port anyways, causing it to fail, and again causing the startup to be interrupted by missing onion name.

Try it yourself. Let me know, how it goes. Try getting 2 instances up on the same machine and not collided by ports. It sure used to work with manual port assignments with config, but to recompile 4 different versions with different ports mentioned in the source code, that is a bit too much useless work. It's not impossible, neither non-doable, but you simply cannot alter the 9089 port easily. Or get 2 daemons to work with existing settings, which used to work.

This would be easy case, if I just moved the wallets to another containers keeping them isolated from eachothers, so the port collision won't happen, but that shouldn't be needed, since it sure USED to work.

**Comment by Ondalf** [comment]
Okay. Pinned down a bit. 4.0.1 tor squashed update caused this havoc. 4.0.0 works after slight edit with configure.ac.

**Comment by michpiatek** [comment]
You know you need multiple hidden service ports for tor? I run tor with:

`tor --SocksPort 9050 --ignore-missing-torrc -f ~/tor_test/torrc --HiddenServiceDir ~/tor_test/tor/onion --HiddenServicePort 21102 --HiddenServiceDir ~/test_multiple_verge/tor/onion --HiddenServicePort 21103`

which creates two different hidden services. First dir is in my first verge dir, second in my second verge dir. Then I start them with:

`VERGE-qt -tor=127.0.0.1:9050 -port=HIDDEN_SERV_PORT -datadir=NTH_VERGE_DIR`
e.g.
`VERGE-qt -tor=127.0.0.1:9050 -port=21103 -datadir=/home/srgn/test_multiple_verge`

and:
![image](https://user-images.githubusercontent.com/7089809/34775383-48d80e92-f613-11e7-85ab-b22b4a4eec0d.png)

**Comment by michpiatek** [comment]
@Ondalf One more thing - you need to have /tor/onion dirs in your wallet directories with 700 access permissions to onion dir.

I agree with the statement that's a bit more painful with tor but it's totally doable. Maybe some official tutorial on how to do it should be published.

**Comment by Ondalf** [comment]
Oh, that clears up the thing quite nicely. Let me try. I'll report back. Actually, since if no "-tor" is specified, it goes by defaults, which results running tor with https://github.com/vergecurrency/VERGE/blob/master/src/net.cpp#L1647 unless torrc is in place for it. So if I simply put one wallet to use a bit customized torrc, get it online and connect other wallets via that service, it *should* work generally. I tried this actually before, but those HiddenServicePorts were unclear to me. Or simply just run tor separately.

**Comment by ocminer** [comment]
mmh I received no info that there will be an update necessary

**Comment by justinvforvendetta** [comment]
hey @ocminer can you make a pr on our site and add suprnova?

**Comment by ocminer** [comment]
Sure, what's the repo for the site ?

**Comment by Ondalf** [comment]
Works! Required a bit tinkering, but finally works. Single tor instance, 4 wallets. All good :)

**Comment by michpiatek** [comment]
@Ondalf Good to hear that!

**Comment by justinvforvendetta** [comment]
@ocminer https://github.com/vergecurrency/vergecurrency.com thanks man! glad to see suprnova is still kicking ass!

**Comment by justinvforvendetta** [comment]
@Ondalf what pool do you run?
@ocminer you are on the 4.0.1 now, right?

**Comment by RaDiuM-21** [comment]
Does the frozen transactions issue also affect third-party wallets such as Coinomi?

I have two stuck transactions, one of which has been stuck for over a week without confirmation, cannot be found on the blockchain explorer.

**Comment by Ondalf** [comment]
@justinvforvendetta generally, that doesn't matter. I just happen to run YiiMP based one together with small group of 10 people. I just pointed out the troubles with 4.0.1 and case closed, as it seems to work now. Over and out ->

**Comment by justinvforvendetta** [comment]
@Ondalf so you are running 4.0.1 now and its working ok?

**Comment by Ondalf** [comment]
@justinvforvendetta Yes, 4 instances behind single tor daemon. All in same container. It's still syncing, but generally having connection to outside was the one, I didn't have before.

**Comment by justinvforvendetta** [comment]
we set up a clearnet branch for pools/exchanges that dont/cant/wont run tor as well.

**Comment by imthebackwardsman** [comment]
Have the mempools update yet? My stealth tx's are still stuck with 0 confirmations. Is it possible to remove the txs somehow from my local mempool. Importing the private key doesn't seem to work anymore, I might have to try with the 4.0 version.

**Comment by justinvforvendetta** [comment]
most pools have updated, i think the rest are doing it now

**Comment by unv-annihilator** [comment]
zPool claiming to have some issues with this. Should reopen the issue until resolved for all pool, and confirmed. 

https://twitter.com/_zpool_/status/951846773622001664
