### ISSUE TITLE
All blocks orphaned on >4.0 wallets

### ISSUE THREAD

**Issue by ocminer** [vergecurrency/VERGE#502]
Since upgrading to 4.0 and after the hardfork-block all blocks are orphaned.

Older 2.x wallets seem to work fine.

**Comment by crackfoo** [comment]
same here but, I've already complained ever since you released 4.x that it doesn't work....

**Comment by flound1129** [comment]
for fuck's sake FIX THIS

**Comment by Max-Meldrum** [comment]
@flound1129 Yes, i'm sure that pleasant attitude will make things get fixed sooner...

**Comment by flound1129** [comment]
Maybe you should talk to some of my miners who had a hundred plus blocks orphaned, I doubt they'd be as pleasant.

**Comment by flound1129** [comment]
After the third time being told to upgrade and getting screwed over again I'm not exactly in a pleasant mood.

**Comment by justinvforvendetta** [comment]
you run a pool, voluntarily and for profit. isn't keeping track of updates kind of your job in that regard? the problem wasnt even with your pool though, the problem is the pool admins who are oblivious to updates with the coins they host, and have no method of contact and therefore don't update.

**Comment by justinvforvendetta** [comment]
you are free to list/delist anything from your pool at any time. im over here trying to find contacts for pool admins that have no twitter/irc/email available. that's not my job but that's what I'm doing.

**Comment by justinvforvendetta** [comment]
@crackfoo what pool do you run, and were you running the latest codebase last night? about 14 hours ago?

**Comment by ocminer** [comment]
you should design the updates of the coin in a way that older blocks/older wallet versions are rejected. so old wallets should get the orphans are newer wallets shouldn't accept reorgs from older wallets. the shitstorm on twitter is focusing the pools which upgraded and most miners don't understand that the coders here don't seem to manage a hardfork completely. You fork - the chain splits, new wallets are on the new, correct (developer advertised) chain and the older wallets are on their own - discouraged fork.

All this "bitching" and pointless fingerpointing brings you nothing but discouraged pool ops, raving miners at and the end your coin will drop as fast as it went up when McAfee promoted it.

You should honestly finally get your shit together, hire a dev who's experienced with hard forks and code the wallets in a way other coins did a thousand times before.

**Comment by justinvforvendetta** [comment]
@ocminer well we were hoping we could soft fork if everyone updated, but from what we saw last night, your pool, zpool, idcray, and multi pool were still not the majority of the network, so that is the next plan, to simply make the new clients ignore lower versions. we'll hard fork and case closed.

**Comment by flound1129** [comment]
> you run a pool, voluntarily and for profit. isn't keeping track of updates kind of your job in that regard?

uhhhh, we did update, the entire problem started when we updated and it is still not fixed.

@ocminer really said it all, but I'll add the following.

1. To your implication that I am derelict in my duty as a pool op, in fact the opposite is true.  I've spent about 15 hours over the past 5 days updating and resyncing four wallets several times.
2. Is this is a hardfork or not?  If it is, where is the notice of the hardfork?  your twitter updates going back to 11/22 do not contain the word "fork" at all.  Your ANN thread on bitcointalk also does not contain the word fork on the front page or the last few pages.
3. If it's not a hardfork then what was the rush to update to broken code?

I not only contacted you via twitter, I asked in your IRC channel, posted in Github about excessive orphans on 4.x (#487), and also via some of my miners who contacted me directly via email and said they were contact with the dev team.

If that's not doing enough as a pool op, then I wonder what the fuck IS enough?  As far as delisting coins, we will continue to mine it as long as it's profitable to mine, and the market will decide that.  This kind of talk will not net you any points, anywhere.

Get the fork ready, get the exchanges on it and let the people who don't upgrade worry about the consequences, instead of screwing over the people who are on board.

**Comment by crackfoo** [comment]
zpool.ca and yeah I was on the latest. All orphans after the “fork”

**Comment by flound1129** [comment]
Anyway I guess I'll stop bitching and roll back to 2.1 until I see a real fork announcement.  Thanks.

**Comment by justinvforvendetta** [comment]
yeah the issue was that other than supernova, multi pool, zpool, idcray and miningpoolhub, the other pools have no contact info, so the soft fork wasn't successful. it almost was, but not quite. our only option left is a hard fork which we are going to do and well get a hold of you. the rest of the pools imo, are irresponsible. it's their job to be available to not only developers, but anyone who mines on their pool.

**Comment by ahashpool** [comment]
Please add me to the list of pool owners you should contact when you plan big changes.  I run ahashpool.com  .  email: admin at ahashpool dot com

frankly, i really did not find any announcement of any kind wit the word "fork" <- keyword here.  not on your twitter, not on your bitcointalk thread.  That's why we didn't think it was necessary to update.

**Comment by sajphon** [comment]
Yup, please notify me as well. Running a small pool myself.
email: pool at v2 dot sk

**Comment by justinvforvendetta** [comment]
@sajphon @ahashpool hope you guys are updated. i know @ocminer and @flound1129 are

also y ou guys should add yourselves to our website, its in this repo (github.com/vergecurrency/vergecurrency.com)

**Comment by ahashpool** [comment]
@justinvforvendetta 

Thanks for the headsup.  Could you please tell us which branch pool should use?  There's the "master" branch, "mining_tor" branch, and "clearnet" branch.  They don't seem to have the same last few commits.  For example, "master" has that "revert the revert" 794660a commit  , but "clearnet" only has "revert" a5845e.  and "mining_tor" is just way behind.

**Comment by justinvforvendetta** [comment]
4.0clearnet and master are both prepared. pools seem to like clearnet option over tor, so its up to you. theyre both fine though.
