### ISSUE TITLE
Timed out waiting for onion hostname

### ISSUE THREAD

**Issue by knight9175** [vergecurrency/VERGE#551]
# Issue Template
I 'm Unable to start the verge 4.0 or 4.0.1 qt wallets. I haev 3.0 currently installed. I've removed all the .dll files from the install directory, and have placed the two files in the root of that directory. when I run the verge-qt.exe file I get a verge splash screen then a warning window stating : Timed out waiting for onion hostname

## Prerequisites

* [YES ] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [ *] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

<!-- Please delete (for bugs) or (for features) sections that are not relevant to the Issue you are creating.

Running Windows 10 64 Bit. 

## Expected Behavior

expecting wallet to work on install. 

## Current Behavior

Wallet is not working

**Comment by justinvforvendetta** [comment]
try it again as admin. maybe it's a permission issue

**Comment by jrsikors** [comment]
^^^^ on the 4.0.1 fork for stealth 

Don't use the 3.0 one.

**Comment by ironman81** [comment]
Hi, i got the same error. Have been desperately trying to sort this out... I recently executed the unix executable file from the application content folder and captured the below errors in terminal window which gets logged when the above onion hostname issue popups....

**Comment by ironman81** [comment]
/Applications/VERGE-Qt-New2.app/Contents/MacOS/VERGE-Qt ; exit;
Chelvams-Macbook:~ Chelvam$ /Applications/VERGE-Qt-New2.app/Contents/MacOS/VERGE-Qt ; exit;
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Jan 25 13:32:53.724 [notice] Tor 0.3.2.8-rc-dev running on Darwin with Libevent 2.1.8-stable, OpenSSL 1.0.2n, Zlib 1.2.11, Liblzma N/A, and Libzstd N/A.
Jan 25 13:32:53.724 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Jan 25 13:32:53.724 [notice] Configuration file "/Users/Chelvam/Library/Application Support/VERGE/tor/torrc" not present, using reasonable defaults.
Jan 25 13:32:53.727 [notice] Scheduler type KISTLite has been enabled.
Jan 25 13:32:53.728 [notice] Opening Socks listener on 127.0.0.1:9089
Jan 25 13:32:53.728 [warn] Could not bind to 127.0.0.1:9089: Address already in use. Is Tor already running?
Jan 25 13:32:53.728 [warn] Failed to parse/validate config: Failed to bind one of the listener ports.
Jan 25 13:32:53.728 [err] Reading config failed--see warnings above.
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

I checked the Application support verge tor folder and it is empty....

**Comment by ironman81** [comment]
and the debug file contains the below texts.....

VERGE version v4.0.1.0-d458840-funky-beta (2018-01-23 21:49:56 +0100)
Using OpenSSL version OpenSSL 1.0.2n  7 Dec 2017
Startup time: 01/25/18 00:34:32
Default data directory /Users/Chelvam/Library/Application Support/VERGE
Default mining hash algorithm: scrypt
Used data directory /Users/Chelvam/Library/Application Support/VERGE
scrypt: using scrypt-sse2 as built.
dbenv.open LogDir=/Users/Chelvam/Library/Application Support/VERGE/database ErrorFile=/Users/Chelvam/Library/Application Support/VERGE/db.log
Bound to 127.0.0.1:21102
TOR thread started.
No OBFS4 found, not using it.
Onion thread exited.No onion hostname yet, will retry in 2 seconds... (1/8)
No onion hostname yet, will retry in 2 seconds... (2/8)
No onion hostname yet, will retry in 2 seconds... (3/8)
No onion hostname yet, will retry in 2 seconds... (4/8)
No onion hostname yet, will retry in 2 seconds... (5/8)
No onion hostname yet, will retry in 2 seconds... (6/8)
No onion hostname yet, will retry in 2 seconds... (7/8)
No onion hostname yet, will retry in 2 seconds... (8/8)

**Comment by Max-Meldrum** [comment]
the error is caused because it cannot bind to the port 9089 as the port is being used. You could try a full restart of your computer and hope that solves the issue with the port already being used.

Otherwise, you can try run this command in the terminal sudo lsof -i -n -P | grep 9089 and see if 9089 is being used by something else. note: I don't have access to an os x machine, but I believe that command should still work.

@ironman81 As quite a few people are getting this issue only on OS X (I think), I wonder if it is because people have been running a previous version where the port 9089 has not been "closed" properly by the operating system when the wallet has exited (perhaps in a crash etc).

So is anyone getting this issue while installing the wallet for the very first time?

**Comment by knight9175** [comment]
The sudo command did not work, I'm on Windows. 

@sunerock - running as Admin did not work either. 

this is frustrating, I've transfered all my XVG to exchange from my 3.0 wallet. hoping I can get it back here soon.

**Comment by Max-Meldrum** [comment]
@knight9175 Have you tried doing a full system shutdown and starting the computer up again, and testing again?

If that does not work, I think this command works for windows in the cmd application `netstat -an | find "9089" `, was a while ago I used windows, you might have to right click on cmd and open as admin to run the command.

**Comment by Axionkt** [comment]
I can confirm I get the same error message on Windows, freshly rebooted and not because of the port being used by another process.

Bound to 127.0.0.1:21102
TOR thread started.
No OBFS4 found, not using it.
No onion hostname yet, will retry in 2 seconds... (1/8)
No onion hostname yet, will retry in 2 seconds... (2/8)
No onion hostname yet, will retry in 2 seconds... (3/8)
No onion hostname yet, will retry in 2 seconds... (4/8)
Onion thread exited.No onion hostname yet, will retry in 2 seconds... (5/8)
No onion hostname yet, will retry in 2 seconds... (6/8)
No onion hostname yet, will retry in 2 seconds... (7/8)
No onion hostname yet, will retry in 2 seconds... (8/8)

Last working wallet is 4.0

**Comment by ironman81** [comment]
@Max-Meldrum Thanks for the reply. you are right, i found the ports using the following command 

> sudo lsof -i -P | grep -i "listen"

and can see that 9089 is being used by another crypto wallet. How do i force VERGE wallet to use another port ? doesn't it dynamically fix the ports based on availability? 

Forgot to mention, I did restart the computer several times and still had the same issue...

![image](https://user-images.githubusercontent.com/35785252/35380114-73799ae4-020c-11e8-901d-1bdfe854fc39.png)

**Comment by justinvforvendetta** [comment]
tor wants 9089 but you can run tor with a proxy and no default torrc option

**Comment by jrsikors** [comment]
@knight9175  ... i know your issue kind of got hijacked by some Mac people.

Submit a new issue and clarify your OS / version / problem so no one else can hijack .. in other words try to fill out the template :)

**Comment by jrsikors** [comment]
@knight9175  here are some things I would try:

Make a backup of your wallet.dat ...

~do NOT attempt any other wallet other than the latest: 4.0.1 fork for stealth

A)  Delete everything in your data diretory
B)  Try disabling anti virus for 5 minutes

We do not need to troubleshoot your 3.0 Onion issue, because you should not be using the 3.0 wallet.

We want to focus on:
I 'm Unable to start the verge 4.0.1 qt wallets.

We need more information on this issue

**Comment by forrest222** [comment]
i resolved this issue by uninstalling vmware converter which used port 9089 needed by verged.

**Comment by ironman81** [comment]
@justinvforvendetta Hi thanks for your earlier reply. I have few questions with regard to this 9089
1) I think there is no torrc file inside the installation package, so it is running based on the default values which is why it is conflicting with the other wallet which is already using 9089 port. How do i change verge version of tor invoke not to use port 9089 and use another port
2) I would have uninstalled the program had it been any other like quoted above (vmware converter). In my instance the port is used by another wallet and i cant just shut it down or uninstall... I am not a techie, and need your help with one of the following (detailed steps)

         (a) how to run a proxy or
         (b) how to put a torrc file (config file) into the verge tor folder with the necessary options/commands so that we can bypass the default port setting or
         (c) how to run tor with no default torrc option (steps included)

Really appreciate all the effort in this community. The generic issue of the latest wallet not running on mac-os high sierra seems to be wide but i can see that most of them got it resolved when they install the boost either @1.60 or @1.66. 

For those people who are still facing the problem after boost install is due to this torrc port issue. the pop up message just shows time out waiting for onion hostname error but the underlying problem is due to the conflict in initialising Tor and onion because of this conflicting port 9089.

I am coming to this conclusion as a result of the earlier comment by @forrest222 confirming that after uninstall of the vmware converter which was using the same port 9089, the conflict is gone and verge wallet is able to initialise the port and start the service.... It should have never been this complicated to install the wallet.... neverthless having come this far, with your help, I am confident we can find a resolution for this issue which will help not just me but lot of others too....

Thanks again for the support....

**Comment by justinvforvendetta** [comment]
if you're going to use multiple clients that run on tor, you can do this: 

tor --SocksPort 9050 --ignore-missing-torrc --HiddenServiceDir ~/DATADIR/tor/onion --HiddenServicePort 21102

and then start verge using:

VERGE-qt -tor=127.0.0.1:9050 -port=HIDDEN_SERV_PORT -datadir=DATADIR

**Comment by ironman81** [comment]
@justinvforvendetta Thanks for that, will try it out and let you know.

**Comment by justinvforvendetta** [comment]
@ironman81 we will start working on building easier tor config in soon

**Comment by ironman81** [comment]
@justinvforvendetta Thanks that would be really great. Btw, i try to run the tor command on terminal, it says command not found.

**Comment by justinvforvendetta** [comment]
yes, thats because tor is built into the wallet. in this case that i stated, you'd want to sudo apt-get install tor

**Comment by justinvforvendetta** [comment]
and then connect the tor clients to the tor running on your computer

**Comment by knight9175** [comment]
starting a new thread for my issue

**Comment by cracken1002** [comment]
I can confirm that Vmware Converter is problem. I did not have Converter runin, or port 9089 was closed ,i just got same error. I did not uninstall Converter since i need him, i just have killed 3 of his proccesses in task manager and wallet worked. ( you will have to restart windows if you need to use Converter).
