### ISSUE TITLE
blkindex.dat error.

### ISSUE THREAD

**Issue by pthai112** [vergecurrency/VERGE#657]
Hello all.
This is my issues.
I download the blockchain data from https://verge-blockchain.com, following all step at https://verge-blockchain.com/howto . But VERGE Wallte not working.
Some body can help?.
![err](https://user-images.githubusercontent.com/37857594/38007549-225305f4-3274-11e8-927a-3f7e7afec562.JPG).
This is working on WIN 10.

**Comment by pthai112** [comment]
![de](https://user-images.githubusercontent.com/37857594/38011161-81114c60-3286-11e8-8d77-bd748055d6b1.JPG)
![fo](https://user-images.githubusercontent.com/37857594/38011162-8141617a-3286-11e8-98f0-304f1d6c1f69.JPG)
HI. I already updated latest version and disable virus program, however it still occur same error. I send some pictures for information, could you check?.

**Comment by jrsikors** [comment]
if multiple people are having the problem, it might be an  issue with the bootstrap.  Best thing to do is to get rid of the bootstrap and sync manually from 0.  I'm unsure if the problem will be fixed by the time you sync normally... so if you don't want to waste time .. start over with a new data directory (make sure you backup wallet.dat) , and start syncing from 0 without the bootstrap

**Comment by jrsikors** [comment]
there's a new version of the blockchain you can try out -- no promises it works but i'm testing it now:
https://verge-blockchain.com/blockchain/Wallet_v4.x_Verge-Blockchain_2018-March-28.zip

there might have been a problem with the MArch 26th copy

**Comment by jrsikors** [comment]
closing since it's a duplicate -- please follow #656 for updates
