### ISSUE TITLE
Math is hard.

### ISSUE THREAD

**Issue by lambdaknight** [vergecurrency/VERGE#680]
https://github.com/vergecurrency/VERGE/blob/b6c380727ebe285538b9e5ac330176d9e8983f87/src/main.h#L59

Let's go shopping.

**Comment by justinvforvendetta** [comment]
whats wrong with a 7.5 minute drift?

**Comment by sylido** [comment]
Are you fucking kidding us @justinvforvendetta ?
Own up to stupid programming mistakes first.
Second if you want 15 minutes it would be 15 * 60 as multiple people commented on your commit - this is done because we all know there are 60 seconds in a minute and it's not confusing for other programmers when they look at this code in 60 * 60 * 24 * 365 * 5 seconds or 5 fucking years as it's abundantly clear.

If it's a troll it's a damn good one. (free PR tip)

**Comment by justinvforvendetta** [comment]
@sylido what you just said makes no sense, but ok.

**Comment by justinvforvendetta** [comment]
working on a full fork
