### ISSUE TITLE
Electrum wallet issue

### ISSUE THREAD

**Issue by peskyrabbit** [vergecurrency/verge#686]
# Issue Template
I can't send from my Electrum wallet. Please see image for error message.
What does it mean?
## Prerequisites

* [ ] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Steps to Reproduce (for bugs)

* Steps :
1.
2.
3.
4.

## Your Environment

* Verge Release:
* CPU:
* GPU:
* RAM:
* OS:
    - [ ] I'm using Mac
    - [ ] I'm using Linux
    - [ ] I'm using Mac

## Any extra information that might be useful in the debugging process.

[Electrum..wallet.. error message.docx...docx](https://github.com/vergecurrency/VERGE/files/1882573/Electrum.wallet.error.message.docx.docx)

**Comment by jrsikors** [comment]
> Literally, 'NoneType' object has no attribute... means that you are trying to access an attribute or call a method on something that has the value None

I think the only other time I saw this type of error message is when someone was trying to send from a "Watch Only Address"

If I were you -- I would probably create a new wallet and import private keys.  something weird going on with your wallet maybe ?

**Comment by jrsikors** [comment]
https://github.com/vergecurrency/VERGE/issues/504

**Comment by justinvforvendetta** [comment]
try restoring into the tor electrum

**Comment by peskyrabbit** [comment]
I used my public address to create the new wallet. That's probably why I'm getting the error message.
I don't have access to my private keys because they are password locked.
I do know the public addresses where my verge is, that's what's frustrating because I can see the transactions on the blockchain but can't access.
I have tried restoring from seed but only 1 small transaction shows in the new wallet, I don't know why that is. Is there a way of sending direct from the blockchain to a new wallet?
Hope this makes sense as I am not very good at all this, middle aged with no training in computers.

**Comment by jrsikors** [comment]
Sorry man I know it's confusing and frustrating ... I'll try to explain the mechanics into human language :smile: 

This is an example of a public address:
https://verge-blockchain.info/address/DMCvDCyCsuwX4p6WCtuQWEmXfaq4A4ujjj
DMCvDCyCsuwX4p6WCtuQWEmXfaq4A4ujjj = public address

Behind DMCvDCyCsuwX4p6WCtuQWEmXfaq4A4ujjj is a **_PRIVATE KEY_**

If you own DMCvDCyCsuwX4p6WCtuQWEmXfaq4A4ujjj , or it's in one of your wallets (successfully) .. you will be able to extract the private key for DMCvDCyCsuwX4p6WCtuQWEmXfaq4A4ujjj.

Without the PRIVATE KEY , you don't really own DMCvDCyCsuwX4p6WCtuQWEmXfaq4A4ujjj.  So there is no human on earth that could help you.  Blockchain transactions are irreversible.  Even @justinvforvendetta doesn't have access to like a "master console" where he could transfer your funds somewhere.  The ability for ANYONE to do that would make blockchain the worst idea in history.

That being said -- you don't necessarily need the private key all the time to access your funds.

In the case of Electrum -- your public addresses AND private keys are basically "Stored" in your wallet seed.  

So if you saved the Seed and password -- and your computer crashed -- you would simply install Electrum again -- restore your old new wallet, based on the "seed" and password you created.

So -- long story short:
If you don't have the private keys for the addresses with your funds..
and/or you don't have the electrum seed..
and/or you don't have the electrum password
..You are really out of options unfortunately :(

The best you can really hope for is to learn from this experience and make sure you fully remember your seed & password .. and for extra safety, you can keep track of your private keys.

If your funds go to DMCvDCyCsuwX4p6WCtuQWEmXfaq4A4ujjj .. make sure you know the private key associated with DMCvDCyCsuwX4p6WCtuQWEmXfaq4A4ujjj .. so you never have to worry about passwords, seeds, etc.  But be extra careful with securing the private key, because that's all anyone would need to steal your stuff... that's why extracting the private key is bulletproof.  If anyone got your private key, it's game over

**Comment by peskyrabbit** [comment]
Thanks for you time in trying to help.
I guess I have lost 300k of verge coins, FUCK.
How do hackers get in and steal your coins?

**Comment by Positivism** [comment]
Electrum has a cosmetic issue, you should be able to send them.

**Comment by jrsikors** [comment]
I'm not sure what happened to his original wallet ... but basically he doesn't know his password .. and he imported the public address only .. so he's basically only got a "Watch only"

**Comment by jrsikors** [comment]
Step 1 is definitely getting rid of the "Watch Only" part and finding the original electrum wallet file ... if that's how electrum works?  Can you restore just the wallet file?  The password still wouldn't be known though :(

**Comment by jrsikors** [comment]
Did you save your **_C:\users\YOU\AppData\Roaming\Electrum-XVG\wallets\default_wallet_** file ?  

What happened to that original file ?

**Comment by jrsikors** [comment]
You had said this earlier:

> The problem I have is that I can't remember the password to the original wallet so I created a new one using the address where my verge is.

Let's do an inventory summary here .. Do you have either of these:
  -- original default_wallet file .. not the one you have now
  -- the electrum seed

As Justin said earlier .. keep in mind there are 2 different Electrum wallets out there.  Electrum with Tor, and Clearnet Electrum

Electrum with Tor:
https://github.com/vergecurrency/electrum-xvg-tor/releases

Electrum without Tor:
https://github.com/vergecurrency/electrum-xvg/releases

If you have your Electrum seed .. try using it in the "other" electrum.  If you are using Tor, use the non-tor.  If you are using the non-tor, try the Tor.

**Comment by peskyrabbit** [comment]
I have the seed but when I restore using the seed only the transaction for 4.9 transfers over, the other transactions don’t show.

 

I am trying to create a new tor wallet but it’s not working. I have downloaded the file and unzipped it but when I try and open the exe file nothing happens.

**Comment by jrsikors** [comment]
Can you post the TXs and/or the public addresses of both your successful transactions.. as well as the ones you are saying are the missing ones?

I don’t want to keep running in hypotheticals.  If you can provide the info, I will at least confirm on the blockchain where the coins are... And we can explore options from there

**Comment by jrsikors** [comment]
Here's some other things I would try:

1)
Do you have access to any other type of computer?  Even a Mac?
I would maybe try is restoring the electrum seed to a different computer and see if you have better results.

2)
Make a backup of everything in your AppData\Roaming\Electrum-XVG folder  to a jump drive.. and then delete it completely.  Then re-open electrum and try to import the seed. 

3)
There are a bunch of different versions of Electrum XVG here:
https://github.com/vergecurrency/electrum-xvg/releases 
I would probably be trying every version , even though some of the older ones might not have the servers, if you read one of my comments on #613  , search for "nutshell", and you can probably edit the available servers that way

4)
Regarding the Electrum TOR wallet not opening -- if 'nothing happens' -- my guess would be your anti virus / windows defender is blocking it.  If it's not your anti virus -- it might just be the computer you are on is wacky

~~~~~~~~~~~~~~~~~

In your initial document you posted with a screenshot .. it's accurately showing the balance of
https://verge-blockchain.info/address/DDFdUML69w3QMgu9BRbNqe1YrSw5rH7SqS

It says wallet_7 .. which means you are on the 7th or 8th iteration of the wallet.  Which goes back to my one of my other questions -- where is your original default_wallet ?  Did you ever make a backup of it?

I really think my suggestion 2 above would do wonders to clear up and try to start over fresh.  But my suggestion 1 above is basically doing suggestion 2 as well.  You really could use a clean data directory at this point.  But I wouldn't be deleting anything in there just in case it proves useful later.  I would copy it to a jump drive and then delete everything.

**Comment by oustaz** [comment]
Hello I have an different issue and I am hoping someone can help....My problem is I created my wallet in december 2017, I made sure to write down two copies of the seed and stored them in two different spots, now I have ran into computer issues and wanted to restore my wallet but the seed isn't working! I can't explain it I looked up both copies and I am sure I didn't make any mistakes writing it down the next button is still grayed out I feel so powerless I tought the seed can restore the wallet what to do?

**Comment by jrsikors** [comment]
@oustaz 

First -- I would suggest going to
https://github.com/vergecurrency/VERGE/issues

and posting a new issue so we don't get the conversations mixed.

But give this a shot first...
keep in mind there are 2 different Electrum wallets out there. Electrum with Tor, and Clearnet Electrum

Electrum with Tor:
https://github.com/vergecurrency/electrum-xvg-tor/releases

Electrum without Tor:
https://github.com/vergecurrency/electrum-xvg/releases

I would try doing the seed in both.

**Comment by peskyrabbit** [comment]
Hello Jeff,

 

I tried 1, on another computer but no luck.

 

I found a copy of wallet on my computer but I get an error when I try and open the file, see attached.

Do you know what it means?

 

In regards to 2, where do I find that file?

 

Thanks

John

**Comment by jrsikors** [comment]
I don't see an attachment sorry.  please try to re-post !

**Comment by peskyrabbit** [comment]
From: Giovanni Recchia <johnr@riverland.net.au> 
Sent: Thursday, 12 April 2018 7:30 PM
To: 'vergecurrency/VERGE' <reply@reply.github.com>
Subject: RE: [vergecurrency/VERGE] Electrum wallet issue (#686)

 

Hello Jeff,

 

I tried 1, on another computer but no luck.

 

I found a copy of wallet on my computer but I get an error when I try and open the file, see attached.

Do you know what it means?

 

In regards to 2, where do I find that file?

 

Thanks

John
