### ISSUE TITLE
Can't send $XVG from electrum-xvg wallet

### ISSUE THREAD

**Issue by DasSmeagle** [vergecurrency/VERGE#702]
Hi,

sorry, I would have liked to add an issue in the electrum-xvg repository, but there is no "issues" tab in that one?

Since at least 2 weeks I cannot send $XVG from my wallet. I am connected to e3.verge-electrum.com. ( that is the only server I can connect to, so was not able to test another server - I tried e1 and e2 and several others I found on the net).

This is how I do it:

I have the target wallet in "Contacts" (my Binance Wallet, used it several times before).

Right click on contact -> Pay to
Enter amount (5500) and fee (4) -> [Send]
Are you sure? -> [Yes]
The fee is unusually high -> [Yes]
(Enter Password) -> [OK]
"Signing Transaction..." (takes very long, I think this was quicker in the past?) While this is shown, Network changes from "green" to "red" to "Arrows" several times. 

**After 2:54 Minutes "error: TX rejected"**

I don't think, there is much I can do "wrong" here, right?

I already installed the wallet on a different computer using my seed. I can see my Balance and history fine but still cannot send any funds.

Please help :(

- Oliver

**Comment by jrsikors** [comment]
see some suggestions on #701  as well...

TX rejected usually means the fee is too low.  I would personally increase it by 1 and keep trying.  I wouldn't go higher than maybe 10 though.

**Comment by DasSmeagle** [comment]
Hmm, really? Even at 2 XVG it tells me, "unusually high fee". I just set it so "high" as I had a transaction stuck one time for 2 weeks after sending it with 2 XVG fee. It was still accepted.

I try to go up with the fee, thanks!

**Comment by jrsikors** [comment]
Justin had a good explanation of WHY the fee is higher on #701 
**_was your balance made by alot of deposits? say your balance is 100 coins. it can be from depositing 1 coin 100 times, or depositing 50 coins twice. when you go to send, if it were from alot of small deposits, then the transaction is bigger because of all the inputs. the 2 50 transactions would be smaller because only 2 inputs. the more inputs, the higher the fee_**

That being said -- that doesn't explain why you get a high fee warning above 1.  I'll make sure it's on on the devs radar if it's not already.

To that point though - I would highly recommend playing around with:
https://github.com/vergecurrency/electrum-xvg-tor/releases

the "electrum xvg with Tor" client.  I don't think they are planning on updating the "non tor" electrum much longer.  It will still work,  but if you want to stay up to date, you want to try to get the "Electrum xvg with Tor" working NOW while you have time and it's less stressful :)

**Comment by DasSmeagle** [comment]
@jrsikors Thank you very much, I didn't know that. Yes, my balance is from a lot of small deposits. It's the result of mining for several months and deposits come every 3 hours ;) That also explains, why it took so long to process that transaction! I had some big deposits - I guess, big deposits are transfered first, that's why I only had the problem why this last transfer... 

I already tried electrum-xvg-tor. I was able to "import" my wallet, but I was never able to get a connection... I have no idea, why... But will look into it. Is it working for you? Which Server do you use?

Thanks,
- Oliver

**Comment by jrsikors** [comment]
Step 1)  https://github.com/vergecurrency/electrum-xvg-tor/blob/master/lib/network.py
Step 2)  There's a button towards the top right that says "Raw".  Right click and do a "Save link as" ... and save it wherever
Step 3)  Browse to where you have electrum-xvg-tor installed
Step 4)  Go into the "lib folder"
Step 5)  Copy the network.py you downloaded in step 2 and overwrite the network.py
Step 6)  download install and run run TOR: https://www.torproject.org/download/download
Step 7)  open electrum-xvg-tor

I have auto-connect UNchecked
I have Use SSL checked
I have proxy at Socks5 ... 127.0.0.1 and port 9150
