### ISSUE TITLE
Recovery Phrase

### ISSUE THREAD

**Issue by marpme** [vergecurrency/VERGE#746]
Somehow we need a way to ensure that people will be able to recover there accounts in a simple way, other than saving down the wallet.dat somewhere. (not all of us are techies) 

I'm really thinking about to have something like an 12 word-phrase or something similar, which could recover the account? Feel free to enter new suggestions, maybe we can find a fitting solution.

(thought in combination with the new wallet)

**Comment by jrsikors** [comment]
Just my 2 cents...

I'm personally against the seed phrase concept for a couple reasons:

1)  I think it's as easy as can be to backup wallet.dat

2) You would *have* to save your seed phrase somewhere on a piece of paper or computer, and to me that's a security risk right there.

You don't *have* to write down your passphrase to unlock your wallet.dat.

I think 99% of people 'get it'.  I think there's < 1% of not-the-brightest people who don't figure out how to keep their MONEY secure and backed up.

Even if you implement seed phrase in place of wallet.dat... those <1% are still going to find a way to lose their funds.

Or you will get a different 1% of people who forget their seedphrase and/or get their seedphrase mixed up with the passphrase.

**Comment by jrsikors** [comment]
A feature for the new wallet could be to pop up a reminder.  "You haven't backed up your wallet.dat in 30+ days.  Would you like to back it up now?"

**Comment by marpme** [comment]
@jrsikors You are completely right, haven't thought about those points yet. Thank you for clearing up there.

but still on the second point with: "A feature for the new wallet could be to pop up a reminder", once its backup'd you don't need to remind him, right? 

So we should rather think about to "annoy"/remind the user to do the backup at least once. Probably at startup/setup.

**Comment by jrsikors** [comment]
Due to the "Change Addresses" -- you really need to backup your wallet after every transaction.  Sometimes your coins end up in an address that isn't listed under "Receiving Addresses".  The only way you would know is if you checked the blockchain, and/or went to debug console and did a listaccounts / listaddressgroupings to find them... which is super techie.

To adjust my initial statement:
I'm not COMPLETELY against a seedphrase instead of a wallet.dat

I just want to make sure we aren't implementing it because it's the perfect solution to the problem.

The problem being:
**_Some people don't know how to backup their funds_**

IMO, no solution will help those people.  They are just lost causes :grin: 

So seedphrase or wallet.dat, the lost causes will be lost causes.

**Comment by jrsikors** [comment]
At the end of the day -- crypto in general requires a bit of tech savvy.  

I'm not TRYING to be difficult here.  I like to think of myself as a someone who has solutions/ideas instead of one of those "No that's not going to work" people.

The bonus points the seedphrase idea does have -- is that you could maybe make it work for all the different wallets.
 -QT
 -iPhone
 -Android
 -Electrum

Computer crashes?  No problem,  go download the iPhone app and put in your seedphrase.
iPhone crashed?  No problem, go download the QT wallet and put in your seedphrase.

**Comment by Positivism** [comment]
Majority of people can't even find the wallet.dat.
Securing a file is much harder than an arbitrary string.
You also can't upload a wallet.dat to devices like iPhone, getting one to android would be quite the hassle; with the seedphrase comes portability as you've said @jrsikors.

I see no good reason not to implement a seedphrase.

"I just want to make sure we aren't implementing it because it's the perfect solution to the problem."
If there is a problem why would you NOT want to implement the perfect solution?

**Comment by marpme** [comment]
@justinvforvendetta any statement from your side? 

As it seems, that we are stagnating on the seedphrase solution, maybe you can share some personal insights or experiences?

**Comment by shyrwall** [comment]
You can add a passphrase to a recovery seed. This makes it more secure than a wallet.dat+passphrase since your seed could then be stored anywhere and would be useless without the passphrase. A wallet.dat can be stolen with malware and the passphrase could also be captured.

**Comment by shyrwall** [comment]
Also I don't think VERGE has implemented BIP32 so as soon as you generate a new address, new stealth address for example your old wallet.dat backup would be invalidated. So to be safe you need to backup the wallet.dat every time you've made a transaction.

Also If i'm not mistaken without BIP32 a recovery seed wouldn't work since you can't derive the addresses from the main key.

I will assume justins answer will be that this will be implemented in the coming codebase since this would be the most logical thing and BIP32 would already be in there.

**Comment by erinjudj** [comment]
I had coins in my first verge wallet. then it goes out of sync    I am still mining to it but I cannot pull it up any in my newly sync verge wallet! UGH!!! Anyone, can you please help me?

**Comment by jrsikors** [comment]
Will try to help @erinjudj , can you please post a new issue.  You should also check out:
https://github.com/vergecurrency/VERGE/wiki/Verge-QT-Wallet-FAQ-%26-Common-Issues#funds-arent-showing

**Comment by jrsikors** [comment]
We are closing ALL issues to get a clean slate after the major codebase update.  Please re-submit issue with details if this is still an issue moving forward.

**Comment by Jon1325** [comment]
You need the best recovery expert at REMOTESPYTECH (at) GMAILC0M to rescue you from your crypto theft schemes. Lot of con artists have ventured into the crypto investment space where one tend to lose money on daily basis all with the intend and promise to earn huge profits. No one is bigger than these evil schemes cause this people are smart in their ways. They tend to provide contact agreement with you, get you to a group with individuals who had already invested (but all lies) only to make you feel comfortable to invest your hard earned money. I followed their instructions and invested my money only to discover after few days I’ve been ripped off 5BTC and 8 ETH. I became furious and wanting a revenge. I had contacted few crypto recovery agent but they were all unprofessional until I was introduced to the best crypto tech pro at REMOTESPYTECH (@) GMAILCOM who got back my money with their prowess and experience in handling fund theft. I got all my funds back to the last penny at an affordable charge. Reasons you need to hire this team for your job are they are swift, reliable and are affiliate agency to the FTC which approves their legitimacy. They have previously handled many successful cases.

Email: REMOTESPYTECH@GMAIL.COM

WhatsApp: +1 (352) 870-0844

This team offers other services

Credit Repair

Catch a suspected cheating spouse

Rescue you from a blackmailer (sextortionist)

Phone cloning

Website hacks

Clearing of criminal records

Boost credit scores etc

Get the best and appropriate help now!!!!
