### ISSUE TITLE
Fails to build on Arch Linux with latest OpenSSL and Boost

### ISSUE THREAD

**Issue by msnns** [vergecurrency/VERGE#75]
[Here, for the log.](https://pastebin.com/4vFpf7G7)

There were also bignum errors that I managed to fix myself (but I definitely won't be using my code when it finally builds) because `bignum.h` was using `BN_init` to create bignums (OSSL 1.1 says "use `BN_new` instead").  (This bignum issue is the same as [#48](https://github.com/vergecurrency/VERGE/issues/48)).

I also tried older versions of OpenSSL and Boost (OpenSSL: 1.0.2 and current; Boost: 1.60, 1.63, 1.64, 1.65) and nothing worked.

Using GCC 7.2.0, `OpenSSL 1.1.0e  16 Feb 2017 (Library: OpenSSL 1.1.0f  25 May 2017)`, and Boost 1.65.1.

**Comment by justinvforvendetta** [comment]
ill leave this open until i run some tests with openssl 1.1 and boost higher than 1.63

**Comment by vereten** [comment]
+1 to fix this. Same error when building on Debian/testing

**Comment by justinvforvendetta** [comment]
will push a commit to fix this shortly.

**Comment by vereten** [comment]
Ok, so for now I use workarounds:
(1) temporary install old debian/testing libssl1.0-dev package.
(2) use --with-incompatible-bdb configure switch, because I have libdb5.3-dev, libdb5.3++-dev installed.
And now i have one more issue here:
`./configure --with-incompatible-bdb`
`checking for QT... no`
`checking for QT... no`
`configure: WARNING: Qt dependencies not found; bitcoin-qt frontend will not be built`
`checking whether to build VERGE Core GUI... no (Qt4)`
Seems like a some *qt* package is missing in readme packages list...

**Comment by justinvforvendetta** [comment]
works with openssl 1.1 and boost 1.66 now
