### ISSUE TITLE
VERGE installation on ubuntu fails

### ISSUE THREAD

**Issue by Smurfy303** [vergecurrency/VERGE#782]
Hello,

I am trying to install Verge wallet in ubuntu system. 
I followed all steps that provided in README.md file.
After installation when I hit ./verged or ./verge-qt this gives me an error like,

**VERGED-qt command not found** .Same for **verged**

please help me to install VERGE wallet in ubuntu.

**Comment by marpme** [comment]
We need more information, either provide a log by copying the one of the build.
Or try again with shell script inside the root directory: `chmod u+x go.sh && ./go.sh`

**Comment by malt0se** [comment]
go.sh will likely return the same error.

If compilation has failed, and 181 line statament is false ( "if [ -e ~/VERGE/src/qt/VERGE-qt ]; then" )

then case go.sh will nonetheless try to execute VERGE-qt at line 263. 

But VERGE-qt does not exist, because if compilation has failed, then there was no "sudo make install", therefore, there will be the same "VERGED-qt command not found"

**Comment by justinvforvendetta** [comment]
"VERGED-qt command not found .Same for verged"

neither of these exist after compilation. they are ./VERGE-qt and ./VERGEd (case sensitive)

also, go.sh will definitely work if you are using an ubuntu system. ive tested it on 16, 17, and 18.

**Comment by malt0se** [comment]
I definitely meant VERGE-qt, just quoted without checking.

I didn't say that go.sh will fail. I said "go.sh will likely return the same error."

If compilation has failed, then there will be no ~/VERGE/src/qt/VERGE-qt and "sudo make install" will not be executed.

Therefore when go.sh will try to execute VERGE-qt at line 263 it will return "VERGE-qt command not found".

This is what i meant, it has nothing to do with ubuntu.

You don't notice this if compilation was successful, but if compilation has failed nothing is going to stop go.sh from trying to execute VERGE-qt (which does't exist)

**Comment by malt0se** [comment]
If compilation has failed, go.sh will just return error about "VERGE-qt command not found", but it will continue to work.

Despite failed compilation it will try to download "complete VERGE Blockchain" and create desktop and menu items.

So it will definitely work, but why?

**Comment by justinvforvendetta** [comment]
i mean go.sh will compile VERGE-qt and VERGEd on an ubuntu system. from the first post, it seems he was trying to type the wrong name because they are both case sensitive.

**Comment by malt0se** [comment]
True.

Most likely wrong names are the reason for the aforementioned error.

I've just presumed, that with go.sh (in case of failed compilation and correct names) there would be the same outcome as if he typed the wrong names, i.e. ".. command not found".

Moreover, things might get even more confusing, as go.sh (despite all errors) would create menu/desktop icons, intuitively indicating that installation has completed successfully.

**Comment by Smurfy303** [comment]
Helli,
 I tried all ways that you tell me in above discussion the error looks like aas below

![error](https://user-images.githubusercontent.com/23695898/42614647-6aaec196-85c4-11e8-92dc-2f60a60b1208.png)

**Comment by malt0se** [comment]
So, compilation has failed indeed and there is no VERGE-qt binary.

As of now, go.sh script has only one checkpoint which you can use to debug this problem.

Try to find the "Compile fail not VERGE-qt present" line in you console and show us the lines before that message.

**Comment by Smurfy303** [comment]
yes, i have got an error like,
![error2](https://user-images.githubusercontent.com/23695898/42616849-4f4fda1c-85cd-11e8-98e9-0ef8a0a47f01.png)

**Comment by malt0se** [comment]
Ok, lets try another way.

Please write the results returned by the following commands:

1.
sudo apt-get update && sudo apt-get -y install git libcanberra-gtk-module lynx unzip libdb4.8-dev libdb4.8++-dev build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils git libboost-all-dev libminiupnpc-dev libqt5gui5 libqt5core5a libqt5dbus5 libevent-dev qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler libqrencode-dev libseccomp-dev libcap-dev

2.
find /usr/lib -name libdb_cxx-4.8.so

3.
grep --include=*.hpp -r '/usr/include' -e "define BOOST_LIB_VERSION" | sed 's/[^0-9]//g'

**Comment by Smurfy303** [comment]
Hiee,

I followed steps that you have told, see
![output](https://user-images.githubusercontent.com/23695898/42621628-efe61398-85db-11e8-8583-4f1915c509cb.png)

**Comment by malt0se** [comment]
cd $HOME/VERGE

wget -O $HOME/boost_1_63_0.zip https://sourceforge.net/projects/boost/files/boost/1.63.0/boost_1_63_0.zip

unzip boost_1_63_0.zip

cd boost_1_63_0

sh bootstrap.sh

sudo ./b2 install

sudo ldconfig

cd ..

./autogen.sh

./configure --with-gui=qt5 --with-boost-libdir=/usr/local/lib/

make -j$(nproc)

**Comment by malt0se** [comment]
//if everything is OK then

sudo make install

**Comment by malt0se** [comment]
// if 163, then just do

cd $HOME/VERGE

./autogen.sh

./configure --with-gui=qt5 --with-boost-libdir=/usr/local/lib/

make -j$(nproc)

sudo make install

**Comment by Smurfy303** [comment]
I am following  steps provideed by you its taking time to install I soon let you know :+1:

**Comment by Smurfy303** [comment]
its not working still :-1:

**Comment by justinvforvendetta** [comment]
paste the results

**Comment by malt0se** [comment]
What command is not working?

And no more screenshots, please

Just copy output of failed command

**Comment by Smurfy303** [comment]
When I used last command,
**sudo make install** it gives me an error like,

>  std::allocator<uint256> >&, bool&, bool&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
> /home/admin1/VERGE/src/walletdb.cpp:206: undefined reference to `CTransaction::CheckTransaction() const'
> collect2: error: ld returned 1 exit status
> Makefile:1840: recipe for target 'VERGEd' failed
> make[2]: *** [VERGEd] Error 1
> make[2]: Leaving directory '/home/admin1/VERGE/src'
> Makefile:4534: recipe for target 'install' failed
> make[1]: *** [install] Error 2
> make[1]: Leaving directory '/home/admin1/VERGE/src'
> Makefile:538: recipe for target 'install-recursive' failed
> make: *** [install-recursive] Error 1

**Comment by Smurfy303** [comment]
Error log is ,

> Makefile:1840: recipe for target 'VERGEd' failed
> Makefile:1898: recipe for target 'test_verge' failed
> Makefile:1858: recipe for target 'qt/VERGE-qt' failed
> make[2]: Leaving directory '/home/admin1/VERGE/src'
> Makefile:1553: recipe for target 'all' failed
> make[1]: Leaving directory '/home/admin1/VERGE/src'
> Makefile:538: recipe for target 'all-recursive' failed
> Making install in tor
> make[1]: Entering directory '/home/admin1/VERGE/tor'
> make[2]: Entering directory '/home/admin1/VERGE/tor'
>  /bin/mkdir -p '/usr/local/bin'
>  /usr/bin/install -c contrib/client-tools/torify '/usr/local/bin'
>  /bin/mkdir -p '/usr/local/etc/tor'
>  /usr/bin/install -c -m 644 src/config/torrc.sample '/usr/local/etc/tor'
>  /bin/mkdir -p '/usr/local/share/tor'
>  /usr/bin/install -c -m 644 src/config/geoip src/config/geoip6 '/usr/local/share/tor'
> make[2]: Leaving directory '/home/admin1/VERGE/tor'
> make[1]: Leaving directory '/home/admin1/VERGE/tor'
> Making install in src
> make[1]: Entering directory '/home/admin1/VERGE/src'
> make  install-am
> make[2]: Entering directory '/home/admin1/VERGE/src'
> Building LevelDB ... Executes: make -C leveldb all
> make[3]: Entering directory '/home/admin1/VERGE/src/leveldb'
> make[3]: Nothing to be done for 'all'.
> make[3]: Leaving directory '/home/admin1/VERGE/src/leveldb'
>   CXXLD    VERGEd
> Makefile:1840: recipe for target 'VERGEd' failed
> make[2]: Leaving directory '/home/admin1/VERGE/src'
> Makefile:4534: recipe for target 'install' failed
> make[1]: Leaving directory '/home/admin1/VERGE/src'
> Makefile:538: recipe for target 'install-recursive' failed

**Comment by justinvforvendetta** [comment]
i forgot to ask, what version of ubuntu?

**Comment by malt0se** [comment]
// As indicated by the last screenshot, it is Xenial.

// Either this will work, or i don't know what is going on:

printf '#!/bin/bash\ncd $HOME/VERGE\n./autogen.sh\n./configure CPPFLAGS="-I/usr/include -O2" LDFLAGS="-L/usr/lib" --with-gui=qt5 --with-boost-libdir=/usr/local/lib/\nmake -j$(nproc)\nsudo make install\n' > verge_script.sh

chmod +x verge_script.sh

./verge_script.sh  2> verge_script.sh.err.log

// And then copy the output of the

cat verge_script.sh.err.log

**Comment by malt0se** [comment]
@Smurfy303, so, did it worked or not?

**Comment by Smurfy303** [comment]
Not working :(

**Comment by malt0se** [comment]
Is that it?
"cat verge_script.sh.err.log" - also not woriking?

**Comment by Smurfy303** [comment]
It's working, I am showing you the last lines of that command,

> /home/admin1/VERGE/src/main.h:520: undefined reference to `nBestHeight'
> libbitcoin_wallet.a(libbitcoin_wallet_a-wallet.o): In function `CMerkleTx::GetDepthInMainChain() const':
> /home/admin1/VERGE/src/main.h:1109: undefined reference to `CMerkleTx::GetDepthInMainChain(CBlockIndex*&) const'
> libbitcoin_wallet.a(libbitcoin_wallet_a-wallet.o): In function `CBlockHeader::SetNull()':
> /home/admin1/VERGE/src/main.h:1216: undefined reference to `nBestHeight'
> libbitcoin_wallet.a(libbitcoin_wallet_a-wallet.o): In function `CBlock::ReadFromDisk(unsigned int, unsigned int, bool)':
> /home/admin1/VERGE/src/main.h:1474: undefined reference to `OpenBlockFile(unsigned int, unsigned int, char const*)'
> libbitcoin_wallet.a(libbitcoin_wallet_a-wallet.o): In function `GetAlgo(int)':
> /home/admin1/VERGE/src/main.h:171: undefined reference to `nBestHeight'
> libbitcoin_wallet.a(libbitcoin_wallet_a-wallet.o): In function `CBlock::ReadFromDisk(unsigned int, unsigned int, bool)':
> /home/admin1/VERGE/src/main.h:1489: undefined reference to `CheckProofOfWork(uint256, unsigned int, int)'
> libbitcoin_wallet.a(libbitcoin_wallet_a-walletdb.o): In function `ReadKeyValue(CWallet*, CDataStream&, CDataStream&, int&, std::vector<uint256, std::allocator<uint256> >&, bool&, bool&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
> /home/admin1/VERGE/src/walletdb.cpp:206: undefined reference to `CTransaction::CheckTransaction() const'
> collect2: error: ld returned 1 exit status
> make[2]: *** [VERGEd] Error 1
> make[1]: *** [install] Error 2
> make: *** [install-recursive] Error 1

**Comment by malt0se** [comment]
@Smurfy303 

Also, there is a possibility that you have the same issue that i've once had.
Eventually i didn't find the cause of the problem, but there is some dirty fix, that i used.
For some reason, during configuration the "out-shared" directory was not created.

In this issue https://github.com/vergecurrency/VERGE/issues/766 same problem was solved by just using sudo with go.sh, assuming that issue was with user permission,

which i highly doubt, because i got this bug randomly on the same OS in the seemingly same conditions.
And i would not recommend using sudo ./go.sh, but do as you please.

After all, i just did "mkdir src/leveldb/out-shared" before compilation.

So, in full this would be:

printf '#!/bin/bash\ncd $HOME/VERGE\nmkdir src/leveldb/out-shared\n./autogen.sh\n./configure CPPFLAGS="-I/usr/include -O2" LDFLAGS="-L/usr/lib" --with-gui=qt5 --with-boost-libdir=/usr/local/lib/\nmake -j$(nproc)\nsudo make install\nVERGE-qt\n' > verge_script.sh

chmod +x verge_script.sh

./verge_script.sh

**Comment by malt0se** [comment]
Just checked this issue again (without aforementioned fix). And got the same error on freshly cloned git repo.

//////////////////
Assembler messages:
Fatal error: can't create out-shared/db/db_bench.o: No such file or directory
make[3]: *** [Makefile:415: out-shared/db/db_bench.o] Error 1
//////////////////

BUT

it turns out, that "src/leveldb/out-shared" direcory WAS created but was not used and was empty.

So, after i've just launched the compilation again (without aforementioned fix, without cleaning, without removing VERGE directory), there was no error. And compilation was successful.

Maybe, for some reason, during compilation, the attempt to copy files in "src/leveldb/out-shared" was made before the "src/leveldb/out-shared" was actually created?

Also, i was wrong - the bug is not that random, but i still think it has nothing to do with user permissions.

However, maybe it is not relevant to the current issue and you've got some different bug.

**Comment by malt0se** [comment]
Ok, "race between directory creation and a build command" - it's leveldb thing - https://github.com/google/leveldb/issues/556

So, using "make" instead of "make -j$(nproc)" or "make -j", seems like helping to avoid the "Fatal error: can't create out-shared/db/db_bench.o: No such file or directory" issue.
