### ISSUE TITLE
Macbook Pro 2014 - Synchronizing with network takes Forever.

### ISSUE THREAD

**Issue by sahh97** [vergecurrency/VERGE#813]
Hey Guys,

I am new to use the Verge wallet. Before i realized that the wallet is not synchronizing, I told a friend of mine to send my verge coins to the address that was provided in the wallet. My first guestion is, why does it take forever for the walet to synchronize with the network and how can I solve the problem? Secondly, will i get my coins once the wallet will be synchronized or I lost them? Please help me out.

Thank you very much!

**Comment by jeepman4403** [comment]
I've been synchronizing for 2 weeks and I'm only 6% done through tor takes forever 


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: sahh97 <notifications@github.com> Date: 10/12/18  1:48 AM  (GMT-05:00) To: vergecurrency/VERGE <VERGE@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [vergecurrency/VERGE] Macbook Pro 2014 - Synchronizing with network takes Forever. (#813) 
Hey Guys,
I am new to use the Verge wallet. Before i realized that the wallet is not synchronizing, I told a friend of mine to send my verge coins to the address that was provided in the wallet. My first guestion is, why does it take forever for the walet to synchronize with the network and how can I solve the problem? Secondly, will i get my coins once the wallet will be synchronized or I lost them? Please help me out.
Thank you very much!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/vergecurrency/VERGE","title":"vergecurrency/VERGE","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/vergecurrency/VERGE"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Macbook Pro 2014 - Synchronizing with network takes Forever. (#813)"}],"action":{"name":"View Issue","url":"https://github.com/vergecurrency/VERGE/issues/813"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/vergecurrency/VERGE/issues/813",
"url": "https://github.com/vergecurrency/VERGE/issues/813",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Macbook Pro 2014 - Synchronizing with network takes Forever. (#813)",
"sections": [
{
"text": "",
"activityTitle": "**sahh97**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@sahh97",
"facts": [
{
"name": "Repository: ",
"value": "vergecurrency/VERGE"
},
{
"name": "Issue #: ",
"value": 813
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"vergecurrency/VERGE\",\n\"issueId\": 813,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"vergecurrency/VERGE\",\n\"issueId\": 813\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/vergecurrency/VERGE/issues/813"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 392384894\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by justinvforvendetta** [comment]
@sahh97 shouldnt take more than a day or two, but you can download the blockchain instead. and yes, your coins will show up when its complete

**Comment by marpme** [comment]
Leaving this as a future reference: https://verge.zendesk.com/hc/en-us/articles/360015942312-Syncing-is-slow-stuck-will-take-forever
