### ISSUE TITLE
Create addresses

### ISSUE THREAD

**Issue by Pele51** [vergecurrency/VERGE#891]
When i created a few addresses on the codebase beta version and tried to delete them after it just worked once, when i mark the address i want to delete it wont work anymore

**Comment by Desolatorbtc** [comment]
@Pele51 every time you request a payment, there will be a new address generated. You can remove the items in "requested payments history" but there is no option to remove the generated addresses in the "receiving addresses" section :
![image](https://user-images.githubusercontent.com/37277151/54078176-0ff13500-42c4-11e9-96fd-7097eb636a8a.png)

**Comment by Pele51** [comment]
@Desolatorbtc im talking about this if i click on it and mark an address before it should get deleted? no?

**Comment by Pele51** [comment]
@Desolatorbtc  I mean if i create some addresses and i mark them then i should be able to delete them after, like in the image below?

![codebase](https://user-images.githubusercontent.com/35359689/54085781-f393dd80-4341-11e9-8f6b-b78dc07ec131.jpg)

**Comment by Pele51** [comment]
Here is a better image 

![codebase1](https://user-images.githubusercontent.com/35359689/54085845-c1cf4680-4342-11e9-8bec-a07d84ae7b28.jpg)

**Comment by jrsikors** [comment]
no QT wallet will let you "delete" receiving addresses... and thank god for that 😄 , otherwise people would be accidentally deleting their addresses and losing their money.

The screen you are referring to is "Requested Payment" , not the actual address.
The screen Desolator posted is from the actual "Receiving Addresses"
![ss1](https://user-images.githubusercontent.com/31370541/54086240-ab5ec600-4315-11e9-964d-abcd0f2c9854.png)

The only way to really 'delete' an address is (USE EXTREME CAUTION ON THIS NEXT STEP) to export all your good private keys, rename/make a backup of your current wallet.dat, delete your wallet.dat, create a new wallet.dat , and import all your good private keys.

**Comment by Pele51** [comment]
Ok thx guys i know u shouldnt delete addresses, but that just wont work for me:

@Pele51 every time you request a payment, there will be a new address generated. You can remove the items in "requested payments history"( and i cant remove the items, thats what i want to say)

**Comment by Desolatorbtc** [comment]
@Pele51 I can't delete the payment requests to stealth address but it works for the normal addresses.

**Comment by justinvforvendetta** [comment]
you can delete your wallet.dat when the wallet is closed, if you want a new address. otherwise deleting the same wallet's addresses would be pointless anyway

**Comment by marpme** [comment]
Well if we offer the deletion button, then it should function properly lol @justinvforvendetta.

This is my take on this issue.

**Comment by Pele51** [comment]
@marpme exactly! i tried it manytimes and just sometimes it works and i can remove one, i tried it also with another member and it worked just fine for him, also for desolatorbtc it seems to work, i dont know why it doesnt work on my wallet

**Comment by marpme** [comment]
Well just tried it on the latest develop branch and it's working properly (you have to select the rows first!)
Will close this issue then, if there's still some errors then re-open this
