### ISSUE TITLE
Suggestion - Data Folder location selection

### ISSUE THREAD

**Issue by CryptoSyndrome** [vergecurrency/VERGE#91]
Suggestion to allow the user to pick the desired **Data Folder** path during wallet installation phase.

**Another work-around (Windows OS)**

- Create a shortcut of **VERGE-qt.exe**
- Right click on the created shortcut then **Properties** , add the following line at **Target** path:

 **-datadir=DRIVE:\DATA_FOLDER_PATH**

Example: 

Target: " D:\verge-3.0\VERGE-qt.exe " -datadir=DRIVE:\DATA_FOLDER_PATH

_Drive: Drive where data folder is located (D: E: F: etc..)_

_DATA_FOLDER_PATH: Exact location of the desired Data folder_

**Comment by nosekefik** [comment]
I can get it working for linux daemon, it will work?

**Comment by jrsikors** [comment]
Closing issue -- since Verge really isn't an "installation" and more of an "unzip these 2 files" :smile:   If Verge ever moves into an "installation" like some of the other QT Wallets, I'm sure code to include custom data directory will be involved.

But for now you got the right idea  on the workaround --- run it with a -datadir=
